//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class acuerdos_comerciales_detalle
    {
        public decimal acde_codigo { get; set; }
        public decimal acde_item { get; set; }
        public Nullable<decimal> acde_cod_marca { get; set; }
        public Nullable<decimal> acde_porcentaje { get; set; }
    }
}
