//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class acuerdos_comerciales_periodo_pago
    {
        public decimal acpp_codigo { get; set; }
        public string acpp_descripcion { get; set; }
        public string acpp_usuario_carga { get; set; }
        public Nullable<System.DateTime> acpp_fecha_carga { get; set; }
        public Nullable<decimal> acpp_nro_entrada { get; set; }
    }
}
