//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class acuerdos_comerciales_tipos_pagos
    {
        public decimal acpa_codigo { get; set; }
        public string acpa_descripcion { get; set; }
        public string acpa_usuario_carga { get; set; }
        public Nullable<System.DateTime> acpa_fecha_carga { get; set; }
        public Nullable<decimal> acpa_nro_entrada { get; set; }
    }
}
