//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class acuerdos_comerciales_tipos
    {
        public decimal acti_codigo { get; set; }
        public string acti_descripcion { get; set; }
        public string acti_usuario_carga { get; set; }
        public Nullable<System.DateTime> acti_fecha_carga { get; set; }
        public Nullable<decimal> acti_nro_entrada { get; set; }
    }
}
