//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class agencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agencias()
        {
            this.cajas = new HashSet<cajas>();
            this.fina_datos_cheques = new HashSet<fina_datos_cheques>();
            this.fina_cajas = new HashSet<fina_cajas>();
            this.fina_boletas_retencion = new HashSet<fina_boletas_retencion>();
            this.fina_datos_tarjetas = new HashSet<fina_datos_tarjetas>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal cod_agcia { get; set; }
        public string nombre { get; set; }
        public string nombre_encargado { get; set; }
        public string email_encargado { get; set; }
        public decimal nro_entrada { get; set; }
        public string usuario { get; set; }
        public Nullable<decimal> cod_dpto { get; set; }
        public Nullable<decimal> cod_ciudad { get; set; }
        public string direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas> cajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fina_datos_cheques> fina_datos_cheques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fina_cajas> fina_cajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fina_boletas_retencion> fina_boletas_retencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fina_datos_tarjetas> fina_datos_tarjetas { get; set; }
    }
}
