//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ajustes_cab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ajustes_cab()
        {
            this.ajustes_detalle = new HashSet<ajustes_detalle>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal nro_ajuste { get; set; }
        public decimal tipo_ajuste { get; set; }
        public decimal cod_agcia { get; set; }
        public decimal cod_motivo { get; set; }
        public string comentario { get; set; }
        public decimal nro_inventario { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public decimal estado { get; set; }
        public string usuario_estado { get; set; }
        public Nullable<System.DateTime> fecha_estado { get; set; }
        public string hora_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ajustes_detalle> ajustes_detalle { get; set; }
        public virtual motivos_ajustes motivos_ajustes { get; set; }
    }
}
