//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class aranceles
    {
        public string cod_empresa { get; set; }
        public string codarancel { get; set; }
        public string codplancta { get; set; }
        public string codplanaux { get; set; }
        public string descrip { get; set; }
        public string tpdef { get; set; }
        public string periodo { get; set; }
    }
}
