//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulos_precios_modificados
    {
        public decimal cod_empresa { get; set; }
        public decimal cod_articulo { get; set; }
        public decimal item { get; set; }
        public decimal precio_anterior { get; set; }
        public decimal precio_actual { get; set; }
        public decimal nro_entrada_factura { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
    }
}
