//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulos_precios
    {
        public decimal cod_empresa { get; set; }
        public decimal cod_articulo { get; set; }
        public decimal cod_politica { get; set; }
        public decimal desde { get; set; }
        public decimal hasta { get; set; }
        public decimal porcentaje { get; set; }
        public decimal precio { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public decimal nro_entrada { get; set; }
        public Nullable<decimal> precio_promocion { get; set; }
        public Nullable<System.DateTime> inicio_promocion { get; set; }
        public Nullable<System.DateTime> fin_promocion { get; set; }
        public Nullable<decimal> porcentaje_patio { get; set; }
        public Nullable<decimal> precio_patio { get; set; }
        public decimal porcentaje_promocion { get; set; }
        public Nullable<decimal> precio_me { get; set; }
    
        public virtual articulos articulos { get; set; }
        public virtual politicas_ventas politicas_ventas { get; set; }
    }
}
