//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articulos()
        {
            this.ajustes_detalle = new HashSet<ajustes_detalle>();
            this.articulos_ctas_contables = new HashSet<articulos_ctas_contables>();
            this.articulos_area = new HashSet<articulos_area>();
            this.articulos_precios = new HashSet<articulos_precios>();
            this.cajas_mov_det = new HashSet<cajas_mov_det>();
            this.camiones_articulos = new HashSet<camiones_articulos>();
            this.corte_inventario_det = new HashSet<corte_inventario_det>();
            this.formulas = new HashSet<formulas>();
            this.formulas1 = new HashSet<formulas>();
            this.movimiento_articulos_det = new HashSet<movimiento_articulos_det>();
            this.movimiento_articulos_det_borra = new HashSet<movimiento_articulos_det_borra>();
            this.politicas_de_venta = new HashSet<politicas_de_venta>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal cod_articulo { get; set; }
        public string cod_alfanumerico { get; set; }
        public string codigo_fabrica { get; set; }
        public decimal tipo_articulo { get; set; }
        public decimal cod_marca { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal cod_unidad { get; set; }
        public decimal stock_minimo { get; set; }
        public decimal stock_actual { get; set; }
        public decimal costo_promedio { get; set; }
        public decimal pct_utilidad { get; set; }
        public decimal cod_moneda_venta { get; set; }
        public decimal precio_venta { get; set; }
        public string codigo_barras { get; set; }
        public decimal inventario { get; set; }
        public decimal cod_impuesto { get; set; }
        public decimal estado { get; set; }
        public string usuario { get; set; }
        public decimal nro_entrada { get; set; }
        public decimal pct_comision_venta { get; set; }
        public decimal pct_comision_cobro { get; set; }
        public decimal precio_venta_mayorista { get; set; }
        public string direccion_imagen { get; set; }
        public decimal costo_promedio_anterior { get; set; }
        public decimal factor_conversion { get; set; }
        public decimal pct_utilidad_mayorista { get; set; }
        public decimal precio_venta_credito { get; set; }
        public decimal pct_utilidad_credito { get; set; }
        public decimal especial { get; set; }
        public decimal costo_ultima_compra { get; set; }
        public decimal permitir_buscar { get; set; }
        public Nullable<decimal> matriz { get; set; }
        public Nullable<decimal> pct_comision_venta_mayorista { get; set; }
        public Nullable<decimal> familia_articulo { get; set; }
        public Nullable<decimal> puntos_promocion { get; set; }
        public Nullable<System.DateTime> vto_promocion { get; set; }
        public Nullable<decimal> puntos_canje { get; set; }
        public Nullable<decimal> cupon { get; set; }
        public decimal cantidad_caja { get; set; }
        public Nullable<decimal> contenido { get; set; }
        public Nullable<System.DateTime> fecha_ultima_compra { get; set; }
        public Nullable<decimal> cantidad_ultima_compra { get; set; }
        public Nullable<decimal> precio_minimo { get; set; }
        public Nullable<decimal> precio_maximo { get; set; }
        public Nullable<decimal> costo_estiba { get; set; }
        public Nullable<decimal> costo_promedio_me { get; set; }
        public Nullable<decimal> costo_promedio_anterior_me { get; set; }
        public Nullable<decimal> costo_ultima_compra_me { get; set; }
        public Nullable<decimal> precio_minimo_me { get; set; }
        public Nullable<decimal> precio_maximo_me { get; set; }
        public Nullable<decimal> permitir_negativo { get; set; }
        public Nullable<decimal> cod_articulo_anterior { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ajustes_detalle> ajustes_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulos_ctas_contables> articulos_ctas_contables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulos_area> articulos_area { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual marcas marcas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulos_precios> articulos_precios { get; set; }
        public virtual tipos_articulos tipos_articulos { get; set; }
        public virtual tipos_impuestos tipos_impuestos { get; set; }
        public virtual unidades_medida unidades_medida { get; set; }
        public virtual unidades_medida unidades_medida1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas_mov_det> cajas_mov_det { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<camiones_articulos> camiones_articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<corte_inventario_det> corte_inventario_det { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formulas> formulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formulas> formulas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_articulos_det> movimiento_articulos_det { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_articulos_det_borra> movimiento_articulos_det_borra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<politicas_de_venta> politicas_de_venta { get; set; }
    }
}
