//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulos_area
    {
        public decimal cod_empresa { get; set; }
        public decimal cod_articulo { get; set; }
        public decimal cod_deposito { get; set; }
        public decimal cod_area { get; set; }
        public decimal cantidad { get; set; }
    
        public virtual articulos articulos { get; set; }
        public virtual depositos_areas depositos_areas { get; set; }
    }
}
