//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditoria
    {
        public decimal nro_entrada { get; set; }
        public decimal item { get; set; }
        public decimal cod_tabla { get; set; }
        public string userid { get; set; }
        public decimal operacion { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string campo { get; set; }
        public string valor_anterior { get; set; }
        public string valor_actual { get; set; }
    
        public virtual tablas_sistema tablas_sistema { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
