//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class bancos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bancos()
        {
            this.conciliacion_bancaria_cab = new HashSet<conciliacion_bancaria_cab>();
            this.conciliacion_bancaria = new HashSet<conciliacion_bancaria>();
            this.disponibilidades = new HashSet<disponibilidades>();
            this.parte_caja = new HashSet<parte_caja>();
            this.series_cheques = new HashSet<series_cheques>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal ejercicio { get; set; }
        public string cta_contable { get; set; }
        public string nombre { get; set; }
        public decimal cod_moneda { get; set; }
        public decimal tipo_cuenta { get; set; }
        public string nro_cuenta { get; set; }
        public string titular { get; set; }
        public decimal saldo_bancario { get; set; }
        public decimal saldo_minimo { get; set; }
        public string formato_cheque { get; set; }
        public decimal nro_entrada { get; set; }
        public string usuario { get; set; }
        public decimal diferido { get; set; }
        public string cta_contable_descarga { get; set; }
    
        public virtual plan_cuentas plan_cuentas { get; set; }
        public virtual tipos_cuentas_bancos tipos_cuentas_bancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conciliacion_bancaria_cab> conciliacion_bancaria_cab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conciliacion_bancaria> conciliacion_bancaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disponibilidades> disponibilidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parte_caja> parte_caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<series_cheques> series_cheques { get; set; }
    }
}
