//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class bienes
    {
        public decimal cod_empresa { get; set; }
        public decimal cod_bien { get; set; }
        public string codigo_alfanumerico { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal cod_grupo { get; set; }
        public System.DateTime fecha_compra { get; set; }
        public decimal valor_compra { get; set; }
        public decimal ano_vida { get; set; }
        public decimal revaluo { get; set; }
        public decimal depreciacion { get; set; }
        public decimal estado { get; set; }
        public decimal nro_entrada { get; set; }
        public string usuario { get; set; }
    
        public virtual grupos_bienes grupos_bienes { get; set; }
    }
}
