//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrador
    {
        public decimal cod_empresa { get; set; }
        public decimal ejercicio { get; set; }
        public decimal nro_asto { get; set; }
        public decimal item { get; set; }
        public System.DateTime fecha_asto { get; set; }
        public string cta_contable { get; set; }
        public decimal tipo_comprobante { get; set; }
        public string comprobante { get; set; }
        public string concepto { get; set; }
        public decimal debito { get; set; }
        public decimal credito { get; set; }
        public decimal operacion { get; set; }
        public decimal flujo_efectivo { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public string hora_carga { get; set; }
        public string usuario_carga { get; set; }
        public decimal traspasado { get; set; }
        public Nullable<System.DateTime> fecha_traspasa { get; set; }
        public string hora_traspasa { get; set; }
        public string usuario_traspasa { get; set; }
    
        public virtual operaciones_borrador operaciones_borrador { get; set; }
        public virtual plan_cuentas plan_cuentas { get; set; }
        public virtual tipos_comprobantes tipos_comprobantes { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
    }
}
