//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajas_mov_det
    {
        public decimal nro_caja { get; set; }
        public decimal nro_habilitacion { get; set; }
        public decimal nro_mvto { get; set; }
        public decimal item { get; set; }
        public decimal cod_concepto { get; set; }
        public decimal cod_empresa { get; set; }
        public decimal cod_articulo { get; set; }
        public string codigo_barras { get; set; }
        public string nombre_articulo { get; set; }
        public decimal cod_impuesto { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public decimal total { get; set; }
        public decimal imponible { get; set; }
        public decimal iva { get; set; }
        public decimal exento { get; set; }
        public decimal otros { get; set; }
        public decimal sub_total { get; set; }
        public decimal descuento { get; set; }
        public decimal neto { get; set; }
        public decimal eliminado { get; set; }
        public string usuario_elimina { get; set; }
        public Nullable<System.DateTime> fecha_elimina { get; set; }
        public string hora_elimina { get; set; }
        public decimal anulado { get; set; }
        public decimal especial { get; set; }
        public decimal tipo_precio { get; set; }
        public string autoriza_tipo_precio { get; set; }
        public decimal costo { get; set; }
        public Nullable<decimal> cod_politica_venta { get; set; }
        public Nullable<decimal> nro_mvto_preventa { get; set; }
        public Nullable<decimal> cod_frente { get; set; }
        public Nullable<decimal> logistica { get; set; }
        public Nullable<decimal> confirmado { get; set; }
        public Nullable<decimal> nro_movimiento_entrega { get; set; }
        public Nullable<decimal> clave_venta { get; set; }
        public Nullable<decimal> nro_anticipo { get; set; }
        public Nullable<decimal> logistica_agcia { get; set; }
        public decimal nro_remision { get; set; }
        public decimal nro_item_remision { get; set; }
        public Nullable<decimal> nro_movimiento_entrega_stock { get; set; }
    
        public virtual articulos articulos { get; set; }
        public virtual conceptos conceptos { get; set; }
        public virtual politicas_ventas politicas_ventas { get; set; }
    }
}
