//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajas_mov_valores
    {
        public decimal nro_caja { get; set; }
        public decimal nro_habilitacion { get; set; }
        public decimal nro_mvto { get; set; }
        public decimal item { get; set; }
        public decimal tipo_ingreso { get; set; }
        public decimal cod_money { get; set; }
        public decimal t_cambio { get; set; }
        public decimal monto { get; set; }
        public Nullable<decimal> cod_entidad { get; set; }
        public Nullable<decimal> numero_valor { get; set; }
        public string deudor { get; set; }
        public Nullable<System.DateTime> fecha_vto_cheque { get; set; }
        public Nullable<decimal> nro_confirmacion { get; set; }
        public decimal nro_retiro { get; set; }
        public Nullable<decimal> cod_emisor_oc { get; set; }
        public Nullable<decimal> cod_empresa { get; set; }
        public decimal clave_caja_regularizacion { get; set; }
        public decimal clave_cheque { get; set; }
        public decimal nro_entrada_nc { get; set; }
        public decimal importe_nc { get; set; }
    
        public virtual entidades_bancarias entidades_bancarias { get; set; }
        public virtual tipos_ingresos tipos_ingresos { get; set; }
    }
}
