//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajas_mov_cobros
    {
        public decimal nro_caja { get; set; }
        public decimal nro_habilitacion { get; set; }
        public decimal nro_mvto { get; set; }
        public decimal cod_empresa { get; set; }
        public decimal operacion { get; set; }
        public decimal nro_entrada { get; set; }
        public decimal nro_cuota { get; set; }
        public decimal nro_pago { get; set; }
        public decimal cod_moneda { get; set; }
        public decimal importe_cuota { get; set; }
        public decimal importe_cuota_loc { get; set; }
        public decimal moneda_cobro { get; set; }
        public decimal importe_cobro { get; set; }
        public decimal importe_cobro_loc { get; set; }
        public decimal nro_ingreso { get; set; }
    }
}
