//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajas_mov_det_anticipo
    {
        public Nullable<decimal> cod_empresa { get; set; }
        public decimal nro_caja { get; set; }
        public decimal nro_habilitacion { get; set; }
        public decimal nro_mvto { get; set; }
        public decimal nro_entrada_fact { get; set; }
        public decimal item { get; set; }
        public Nullable<decimal> cod_concepto { get; set; }
        public Nullable<decimal> cod_articulo { get; set; }
        public string nombre_articulo { get; set; }
        public Nullable<decimal> cod_impuesto { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> retirado { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> imponible { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> exento { get; set; }
        public Nullable<decimal> otros { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> neto { get; set; }
        public Nullable<decimal> tipo_precio { get; set; }
        public string autoriza_tipo_precio { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> cod_politica_venta { get; set; }
        public Nullable<decimal> nro_mvto_preventa { get; set; }
        public Nullable<decimal> cod_frente { get; set; }
        public decimal nro_anticipo { get; set; }
    }
}
