//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class camiones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public camiones()
        {
            this.camiones_articulos = new HashSet<camiones_articulos>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal cod_camion { get; set; }
        public string descripcion { get; set; }
        public string nro_chapa { get; set; }
        public decimal estado { get; set; }
        public string usuario { get; set; }
        public decimal nro_entrada { get; set; }
        public decimal limite_tara { get; set; }
        public decimal cod_chofer { get; set; }
        public Nullable<decimal> cod_transportista { get; set; }
        public string observacion { get; set; }
        public Nullable<System.DateTime> vencimiento_habilitacion { get; set; }
        public string municipio_habilitacion { get; set; }
        public Nullable<decimal> clave_remision_actual { get; set; }
        public string identificador_app { get; set; }
        public string codigo_rastreo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<camiones_articulos> camiones_articulos { get; set; }
        public virtual personas personas { get; set; }
    }
}
