//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class camiones_remisiones
    {
        public decimal cod_empresa { get; set; }
        public decimal cod_camion { get; set; }
        public decimal clave_remision { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public Nullable<System.DateTime> fecha_inicio_traslado { get; set; }
        public string hora_inicio_traslado { get; set; }
        public Nullable<System.DateTime> fecha_fin_traslado { get; set; }
        public string hora_fin_traslado { get; set; }
        public string usuario_carga { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public string hora_salida { get; set; }
        public Nullable<System.DateTime> fecha_llegada { get; set; }
        public string hora_llegada { get; set; }
        public Nullable<System.DateTime> fecha_impresion { get; set; }
        public string hora_impresion { get; set; }
        public string usuario_impresion { get; set; }
        public decimal cod_chofer { get; set; }
    }
}
