//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class camiones_remisiones_det
    {
        public decimal cod_empresa { get; set; }
        public decimal clave_remision { get; set; }
        public decimal item { get; set; }
        public Nullable<decimal> clave_venta { get; set; }
        public Nullable<decimal> cod_articulo { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> cod_persona { get; set; }
        public Nullable<decimal> cod_frente { get; set; }
        public string numero_documento { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public string hora_entrega { get; set; }
        public Nullable<decimal> tipo { get; set; }
        public decimal nro_remision_final { get; set; }
    }
}
