//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class carta_notas_debitos
    {
        public decimal cod_empresa { get; set; }
        public decimal nro_orden { get; set; }
        public string encargado_banco { get; set; }
        public string acreditar_a { get; set; }
        public string nro_cuenta_acredita { get; set; }
        public string concepto { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public string hora_carga { get; set; }
        public string usuario_carga { get; set; }
        public Nullable<System.DateTime> fecha_impresion { get; set; }
        public string hora_impresion { get; set; }
        public string usuario_impresion { get; set; }
    }
}
