//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class cda_detalle
    {
        public decimal cod_empresa { get; set; }
        public decimal ejercicio { get; set; }
        public string cta_contable { get; set; }
        public decimal numero { get; set; }
        public decimal nro_cuota { get; set; }
        public decimal importe { get; set; }
        public Nullable<decimal> importe_me { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public Nullable<System.DateTime> fecha_presentacion { get; set; }
        public Nullable<System.DateTime> fecha_cobro { get; set; }
        public string hora_cobro { get; set; }
        public string usuario_cobro { get; set; }
        public Nullable<decimal> t_cambio_cobro { get; set; }
        public decimal devengado { get; set; }
        public decimal devengado_me { get; set; }
    
        public virtual cda_cabeza cda_cabeza { get; set; }
    }
}
