//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class centros_de_costo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public centros_de_costo()
        {
            this.articulos_ctas_contables = new HashSet<articulos_ctas_contables>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal cod_centro { get; set; }
        public string nombre { get; set; }
        public decimal cod_agcia { get; set; }
        public decimal nro_entrada { get; set; }
        public string usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulos_ctas_contables> articulos_ctas_contables { get; set; }
    }
}
