//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_fiel_descuentos
    {
        public Nullable<decimal> cod_empresa { get; set; }
        public decimal codigo { get; set; }
        public Nullable<System.DateTime> inicio { get; set; }
        public Nullable<System.DateTime> fin { get; set; }
        public Nullable<decimal> monto_desde { get; set; }
        public Nullable<decimal> tipo_articulo { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
        public Nullable<decimal> monto_hasta { get; set; }
    }
}
