//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class coeficientes_revaluo
    {
        public System.DateTime fecha_cierre { get; set; }
        public decimal mes { get; set; }
        public decimal coeficiente { get; set; }
        public string usuario { get; set; }
        public decimal nro_entrada { get; set; }
    }
}
