//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class conceptos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public conceptos()
        {
            this.cajas_mov_det = new HashSet<cajas_mov_det>();
        }
    
        public decimal cod_concepto { get; set; }
        public string descripcion { get; set; }
        public string sigla { get; set; }
        public string usuario { get; set; }
        public decimal nro_entrada { get; set; }
        public string operacion { get; set; }
        public decimal otros_ingresos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas_mov_det> cajas_mov_det { get; set; }
    }
}
