//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class conciliacion_bancaria_cab
    {
        public decimal cod_empresa { get; set; }
        public decimal nro_conciliacion { get; set; }
        public decimal ejercicio { get; set; }
        public string cta_contable { get; set; }
        public System.DateTime fecha_corte { get; set; }
        public decimal saldo_anterior { get; set; }
        public decimal total_detalle { get; set; }
        public decimal saldo_final { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public string hora_carga { get; set; }
        public string usuario_carga { get; set; }
        public decimal estado { get; set; }
        public Nullable<System.DateTime> fecha_proceso { get; set; }
        public string hora_proceso { get; set; }
        public string usuario_proceso { get; set; }
        public Nullable<decimal> saldo_extracto { get; set; }
    
        public virtual bancos bancos { get; set; }
    }
}
