//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class controla_meses
    {
        public decimal cod_empresa { get; set; }
        public decimal ejercicio { get; set; }
        public decimal num_mes { get; set; }
        public decimal anho { get; set; }
        public decimal apertura { get; set; }
        public Nullable<System.DateTime> fecha_apertura { get; set; }
        public string usuario_apertura { get; set; }
        public decimal cierre { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public string usuario_cierre { get; set; }
    
        public virtual meses meses { get; set; }
        public virtual periodos_fiscales periodos_fiscales { get; set; }
    }
}
