//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class contgral
    {
        public decimal registro { get; set; }
        public System.DateTime fecha_op { get; set; }
        public string nombre_sistema { get; set; }
        public string nombre_contador { get; set; }
        public string ruc_contador { get; set; }
        public decimal alarma { get; set; }
        public string mensaje { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string movil { get; set; }
        public string email { get; set; }
        public string ruta_sistema { get; set; }
        public decimal iva1 { get; set; }
        public decimal iva2 { get; set; }
        public decimal nro_entrada { get; set; }
        public string usuario { get; set; }
        public Nullable<decimal> cantidad_licencia { get; set; }
        public decimal tipo_licencia { get; set; }
        public string desarrollador { get; set; }
        public Nullable<decimal> tipo_orden_pago { get; set; }
        public decimal redondear_precio { get; set; }
        public string ip_servidor { get; set; }
        public string hora_cierre_dia { get; set; }
    }
}
