//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class corte_inventario_cab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public corte_inventario_cab()
        {
            this.corte_inventario_det = new HashSet<corte_inventario_det>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal nro_inventario { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime fecha_corte { get; set; }
        public string hora_corte { get; set; }
        public string usuario_corte { get; set; }
        public Nullable<decimal> estado { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public string hora_cierre { get; set; }
        public string usuario_cierre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<corte_inventario_det> corte_inventario_det { get; set; }
    }
}
