//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizaciones
    {
        public System.DateTime fecha { get; set; }
        public decimal item { get; set; }
        public decimal cod_money { get; set; }
        public decimal cambio_compra { get; set; }
        public decimal cambio_venta { get; set; }
        public decimal nro_entrada { get; set; }
        public string usuario { get; set; }
    
        public virtual monedas monedas { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
