//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class datos_presupuestos_pagos
    {
        public decimal nro_lote { get; set; }
        public decimal item { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public decimal nro_entrada_fact { get; set; }
        public System.DateTime fecha_factura { get; set; }
        public string nombre_proveedor { get; set; }
        public decimal nro_orden { get; set; }
        public Nullable<decimal> importe_pagado { get; set; }
        public string cta_contable { get; set; }
        public string nombre_cuenta { get; set; }
        public Nullable<decimal> presupuesto_codigo { get; set; }
        public string presupuesto_nombre { get; set; }
        public Nullable<decimal> proporcion_pago { get; set; }
    }
}
