//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class depositos_areas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public depositos_areas()
        {
            this.ajustes_detalle = new HashSet<ajustes_detalle>();
            this.ajustes_detalle1 = new HashSet<ajustes_detalle>();
            this.articulos_area = new HashSet<articulos_area>();
            this.corte_inventario_det = new HashSet<corte_inventario_det>();
            this.stock_mensual = new HashSet<stock_mensual>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal cod_deposito { get; set; }
        public decimal cod_area { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string usuario { get; set; }
        public decimal nro_entrada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ajustes_detalle> ajustes_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ajustes_detalle> ajustes_detalle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulos_area> articulos_area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<corte_inventario_det> corte_inventario_det { get; set; }
        public virtual depositos depositos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock_mensual> stock_mensual { get; set; }
    }
}
