//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class despachos_aranceles
    {
        public decimal desa_cod_empresa { get; set; }
        public decimal desa_codigo { get; set; }
        public string desa_cta_contable { get; set; }
        public string desa_descripcion { get; set; }
        public string desa_definicion { get; set; }
    }
}
