//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class despachos
    {
        public decimal desp_cod_empresa { get; set; }
        public decimal desp_ejercicio { get; set; }
        public decimal desp_cod_despachante { get; set; }
        public decimal desp_nro_despacho { get; set; }
        public System.DateTime desp_fecha { get; set; }
        public string desp_descripcion { get; set; }
        public string desp_transporte { get; set; }
        public decimal desp_imponible { get; set; }
        public Nullable<decimal> notadepfiscal { get; set; }
        public Nullable<System.DateTimeOffset> desp_fecha_finiquito { get; set; }
        public string desp_nro_entrada { get; set; }
        public string desp_pais_origen { get; set; }
        public string desp_registro_entrada_nro { get; set; }
        public System.DateTimeOffset desp_fecha_carga { get; set; }
        public decimal desp_peso_neto { get; set; }
        public decimal desp_peso_bruto { get; set; }
        public decimal desp_cod_money { get; set; }
        public decimal desp_t_cambio { get; set; }
        public string desp_nro_liquidacion { get; set; }
        public Nullable<System.DateTimeOffset> desp_fecha_liquidacion { get; set; }
        public decimal desp_total_exento { get; set; }
        public decimal desp_total_gravado { get; set; }
        public decimal desp_total_iva { get; set; }
        public Nullable<decimal> desp_saldo { get; set; }
        public string desp_ley60_90 { get; set; }
        public string nrodecreto { get; set; }
        public decimal desp_tasa_cambio { get; set; }
        public Nullable<decimal> desp_nro_transaccion { get; set; }
        public decimal desp_tasa_vi { get; set; }
        public decimal valorimpdecreto { get; set; }
        public decimal desp_tasa_vid { get; set; }
        public string desp_regimen_normal { get; set; }
        public Nullable<decimal> desp_nro_pedido { get; set; }
        public string desp_nro_solicitud { get; set; }
        public string desp_nro_ord_compra { get; set; }
        public Nullable<decimal> desp_nro_op { get; set; }
        public decimal desp_tasa_cambio_costo_me { get; set; }
        public decimal desp_cod_money_costo_me { get; set; }
        public decimal desp_cod_money_flete_seguro { get; set; }
        public decimal desp_total_flete { get; set; }
        public decimal desp_total_seguro { get; set; }
        public string desp_getfactor_gastimp { get; set; }
        public string desp_asentado_cierre { get; set; }
        public Nullable<decimal> desp_nro_transacion_cierre { get; set; }
        public decimal desp_valorimponible_otros { get; set; }
        public decimal desp_iva_despacho { get; set; }
        public string desp_tipo_despacho { get; set; }
        public string desp_cta_contable { get; set; }
        public string planauxdesp { get; set; }
        public string cod_sucursal { get; set; }
        public Nullable<decimal> desp_cod_aduana { get; set; }
        public Nullable<decimal> desp_nro_asto { get; set; }
    }
}
