//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class despachos_liquidaciones
    {
        public decimal desl_cod_empresa { get; set; }
        public decimal desl_ejercicio { get; set; }
        public decimal desl_cod_despachante { get; set; }
        public decimal desl_nro_despacho { get; set; }
        public decimal desl_linea { get; set; }
        public decimal desl_cod_arancel { get; set; }
        public Nullable<decimal> desl_cod_proveedor { get; set; }
        public Nullable<decimal> desl_tipo_factura { get; set; }
        public System.DateTime desl_fecha_emision { get; set; }
        public decimal desl_nro_comprobante { get; set; }
        public string desl_afecta_costo { get; set; }
        public decimal desl_exento { get; set; }
        public decimal desl_gravado { get; set; }
        public decimal desl_iva { get; set; }
        public string desl_cta_contable { get; set; }
        public string codplanaux { get; set; }
        public string desl_concepto { get; set; }
        public string desl_libroiva { get; set; }
        public string periodo { get; set; }
        public string desl_timbrado { get; set; }
        public string af_valorimponible { get; set; }
        public decimal desl_total_aplicado { get; set; }
        public string desl_tipo_iva { get; set; }
        public string codinciso { get; set; }
        public Nullable<decimal> desl_nro_retencion { get; set; }
        public Nullable<System.DateTime> desl_fecha_retencion { get; set; }
        public Nullable<decimal> desl_monto_retencion { get; set; }
        public Nullable<decimal> desl_porc_iva { get; set; }
        public string desl_timbrado_retencion { get; set; }
    }
}
