//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class disponibilidades
    {
        public decimal cod_empresa { get; set; }
        public decimal ejercicio { get; set; }
        public string cta_contable { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal cod_money { get; set; }
        public decimal saldo_anterior { get; set; }
        public decimal ingresos { get; set; }
        public decimal egresos { get; set; }
        public decimal saldo_anterior_gs { get; set; }
        public decimal ingresos_gs { get; set; }
        public decimal egresos_gs { get; set; }
        public string cta_conjunta { get; set; }
        public string nombre_listado { get; set; }
    
        public virtual bancos bancos { get; set; }
    }
}
