//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos_inutilizados
    {
        public decimal cod_empresa { get; set; }
        public decimal tipo_documento { get; set; }
        public decimal numero { get; set; }
        public string motivo_inutiliza { get; set; }
        public System.DateTime fecha_inutiliza { get; set; }
        public string hora_inutiliza { get; set; }
        public string usuario_inutiliza { get; set; }
    }
}
