//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class emisores_oc
    {
        public decimal cod_emisor { get; set; }
        public string nombre_emisor { get; set; }
        public decimal cod_persona { get; set; }
        public decimal nro_entrada { get; set; }
    }
}
