//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresas()
        {
            this.articulos = new HashSet<articulos>();
            this.cajas_fondo_fijo = new HashSet<cajas_fondo_fijo>();
            this.fondo_fijo_anulados = new HashSet<fondo_fijo_anulados>();
            this.marcas = new HashSet<marcas>();
            this.periodos_fiscales = new HashSet<periodos_fiscales>();
            this.personas = new HashSet<personas>();
            this.presupuesto_items = new HashSet<presupuesto_items>();
            this.tipos_articulos = new HashSet<tipos_articulos>();
            this.usuarios_empresas = new HashSet<usuarios_empresas>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal tipo_empresa { get; set; }
        public string nombre_empresa { get; set; }
        public string razon_social { get; set; }
        public decimal cod_identificador { get; set; }
        public string identificador { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string movil { get; set; }
        public decimal utilizar_serie_factura { get; set; }
        public string activo { get; set; }
        public string pasivo { get; set; }
        public string patrimonio { get; set; }
        public string ingresos { get; set; }
        public string egresos { get; set; }
        public string orden_debito { get; set; }
        public string orden_credito { get; set; }
        public string cta_utilidad_anterior { get; set; }
        public string cta_utilidad_actual { get; set; }
        public string cta_iva_debito_10 { get; set; }
        public string cta_iva_debito_5 { get; set; }
        public string cta_iva_credito_10 { get; set; }
        public string cta_iva_credito_5 { get; set; }
        public string cta_caja_gs { get; set; }
        public string cta_caja_me { get; set; }
        public Nullable<decimal> ejercicio_inicial { get; set; }
        public Nullable<decimal> porcentaje_retencion { get; set; }
        public Nullable<decimal> monto_minimo_retencion { get; set; }
        public string contacto { get; set; }
        public string contador_encargado { get; set; }
        public string ruc_contador { get; set; }
        public string representante_legal { get; set; }
        public decimal nro_entrada { get; set; }
        public decimal estado { get; set; }
        public string usuario { get; set; }
        public string cta_retencion { get; set; }
        public string cta_fluctuacion_ingreso { get; set; }
        public string cta_fluctuacion_egreso { get; set; }
        public decimal bloqueo_cap_cac { get; set; }
        public decimal dias_habil_cap_cac { get; set; }
        public string ruc_representante { get; set; }
        public string nro_timbrado { get; set; }
        public Nullable<System.DateTime> vto_timbrado { get; set; }
        public string nro_timbrado_nc { get; set; }
        public Nullable<System.DateTime> vto_timbrado_nc { get; set; }
        public decimal tipo_fondo_fijo { get; set; }
        public string cta_certificado_cap { get; set; }
        public string cta_certificado_cac { get; set; }
        public string cta_retencion_5 { get; set; }
        public decimal integrar_stock_conta { get; set; }
        public string cta_mercaderias { get; set; }
        public Nullable<decimal> utiliza_serie_cheque { get; set; }
        public string cta_ventas_10 { get; set; }
        public string cta_ventas_5 { get; set; }
        public string cta_ventas_exento { get; set; }
        public string cta_tarjeta_gs { get; set; }
        public string cta_tarjeta_me { get; set; }
        public string cta_adelantos_gs { get; set; }
        public string cta_adelantos_me { get; set; }
        public string cta_contable_costos { get; set; }
        public string cta_contable_descuentos { get; set; }
        public string cta_contable_devoluciones { get; set; }
        public Nullable<decimal> monto_puntuacion1 { get; set; }
        public Nullable<decimal> equivalencia_puntuacion1 { get; set; }
        public Nullable<decimal> monto_puntuacion2 { get; set; }
        public Nullable<decimal> equivalencia_puntuacion2 { get; set; }
        public string cta_contable_inventario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulos> articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas_fondo_fijo> cajas_fondo_fijo { get; set; }
        public virtual tipos_identificadores tipos_identificadores { get; set; }
        public virtual tipos_empresas tipos_empresas { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fondo_fijo_anulados> fondo_fijo_anulados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<marcas> marcas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<periodos_fiscales> periodos_fiscales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personas> personas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<presupuesto_items> presupuesto_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipos_articulos> tipos_articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios_empresas> usuarios_empresas { get; set; }
    }
}
