//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class estibas_det
    {
        public decimal cod_empresa { get; set; }
        public decimal clave_venta { get; set; }
        public Nullable<decimal> cod_articulo { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public decimal cod_empleado { get; set; }
        public Nullable<System.DateTime> fecha_carga { get; set; }
        public string hora_carga { get; set; }
        public string usuario_carga { get; set; }
        public Nullable<decimal> nro_liquidacion { get; set; }
    }
}
