//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturas_cab_temp
    {
        public decimal cod_empresa { get; set; }
        public decimal operacion { get; set; }
        public decimal nro_entrada { get; set; }
        public Nullable<decimal> tipo_factura { get; set; }
        public string nro_factura { get; set; }
        public string nro_factura_legal { get; set; }
        public string nota_credito { get; set; }
        public Nullable<decimal> cod_persona { get; set; }
        public Nullable<decimal> cod_rubro { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public Nullable<System.DateTime> fecha_vto { get; set; }
        public Nullable<decimal> cod_money { get; set; }
        public Nullable<decimal> t_cambio { get; set; }
        public Nullable<decimal> imponible { get; set; }
        public Nullable<decimal> imponible10 { get; set; }
        public Nullable<decimal> imponible5 { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> iva10 { get; set; }
        public Nullable<decimal> iva5 { get; set; }
        public Nullable<decimal> exenta { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> pct_descuento { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> neto { get; set; }
        public Nullable<decimal> a_abonar { get; set; }
        public Nullable<decimal> abonado { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<decimal> imponible_gs { get; set; }
        public Nullable<decimal> imponible10_gs { get; set; }
        public Nullable<decimal> imponible5_gs { get; set; }
        public Nullable<decimal> iva_gs { get; set; }
        public Nullable<decimal> iva10_gs { get; set; }
        public Nullable<decimal> iva5_gs { get; set; }
        public Nullable<decimal> exenta_gs { get; set; }
        public Nullable<decimal> total_gs { get; set; }
        public Nullable<decimal> descuento_gs { get; set; }
        public Nullable<decimal> neto_gs { get; set; }
        public Nullable<decimal> a_abonar_gs { get; set; }
        public Nullable<decimal> provisionar { get; set; }
        public Nullable<decimal> nro_asto { get; set; }
        public string cta_credito { get; set; }
        public Nullable<decimal> fondo_fijo { get; set; }
        public Nullable<decimal> nro_caja { get; set; }
        public Nullable<decimal> utiliza_serie { get; set; }
        public Nullable<System.DateTime> fecha_carga { get; set; }
        public string hora_carga { get; set; }
        public string usuario_carga { get; set; }
        public Nullable<System.DateTime> fecha_provisiona { get; set; }
        public string hora_provisiona { get; set; }
        public string usuario_provisiona { get; set; }
        public Nullable<System.DateTime> fecha_elimina { get; set; }
        public string hora_elimina { get; set; }
        public string usuario_elimina { get; set; }
        public Nullable<System.DateTime> fecha_factura_legal { get; set; }
        public string hora_factura_legal { get; set; }
        public string usuario_factura_legal { get; set; }
        public Nullable<System.DateTime> fecha_impresion_factura { get; set; }
        public string hora_impresion_factura { get; set; }
        public string usuario_impresion_factura { get; set; }
        public Nullable<decimal> nro_asto_elim { get; set; }
        public string nro_referencia { get; set; }
        public Nullable<decimal> otros { get; set; }
        public Nullable<decimal> otros_gs { get; set; }
        public Nullable<decimal> nro_entrada_fact { get; set; }
        public Nullable<decimal> cod_agcia { get; set; }
        public Nullable<decimal> nro_lote { get; set; }
        public Nullable<System.DateTime> fecha_lote { get; set; }
        public string hora_lote { get; set; }
        public string usuario_lote { get; set; }
        public string nro_timbrado { get; set; }
        public Nullable<System.DateTime> fecha_recibe { get; set; }
        public string hora_recibe { get; set; }
        public string usuario_recibe { get; set; }
        public Nullable<decimal> certificado { get; set; }
        public Nullable<decimal> nro_entrada_certificado { get; set; }
        public Nullable<decimal> nro_entrada_agcia { get; set; }
        public Nullable<decimal> monto_retencion { get; set; }
        public Nullable<decimal> monto_retencion_gs { get; set; }
        public Nullable<decimal> cod_vendedor { get; set; }
        public Nullable<decimal> tipo_solicitud { get; set; }
    }
}
