//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturas_det
    {
        public decimal cod_empresa { get; set; }
        public decimal operacion { get; set; }
        public decimal nro_entrada { get; set; }
        public decimal item { get; set; }
        public decimal ejercicio { get; set; }
        public string cta_contable { get; set; }
        public string concepto { get; set; }
        public decimal debito { get; set; }
        public decimal credito { get; set; }
        public decimal pct_iva { get; set; }
        public decimal debito_gs { get; set; }
        public decimal credito_gs { get; set; }
    }
}
