//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturas_cuotas
    {
        public decimal cod_empresa { get; set; }
        public decimal operacion { get; set; }
        public decimal nro_entrada { get; set; }
        public decimal nro_cuota { get; set; }
        public decimal nro_pago { get; set; }
        public System.DateTime fecha_vto { get; set; }
        public decimal importe { get; set; }
        public decimal importe_gs { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<decimal> nro_comprobante { get; set; }
        public Nullable<decimal> nro_ingreso_op { get; set; }
        public Nullable<decimal> clave_cheque { get; set; }
        public decimal importe_nc { get; set; }
        public decimal importe_nc_gs { get; set; }
        public decimal imponible10 { get; set; }
        public decimal imponible5 { get; set; }
        public decimal iva10 { get; set; }
        public decimal iva5 { get; set; }
        public decimal exenta { get; set; }
    
        public virtual facturas_cab facturas_cab { get; set; }
    }
}
