//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_datos_cheques
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fina_datos_cheques()
        {
            this.fina_movimientos_caja = new HashSet<fina_movimientos_caja>();
        }
    
        public decimal che_cod_empresa { get; set; }
        public decimal che_codigo { get; set; }
        public decimal che_cod_sucursal { get; set; }
        public decimal che_tipo { get; set; }
        public decimal che_cod_banco { get; set; }
        public string che_nro_serie { get; set; }
        public decimal che_nro_cheque { get; set; }
        public string che_nombre_cheque { get; set; }
        public System.DateTime che_fecha_vencimiento { get; set; }
        public System.DateTime che_fecha_carga { get; set; }
        public Nullable<System.TimeSpan> che_hora_carga { get; set; }
        public string che_usuario_carga { get; set; }
        public Nullable<System.DateTime> che_fecha_cobro { get; set; }
        public Nullable<System.TimeSpan> che_hora_descarga { get; set; }
        public string che_usuario_descarga { get; set; }
        public decimal che_cod_moneda { get; set; }
        public decimal che_tasa_cambio { get; set; }
        public decimal che_importe { get; set; }
        public decimal che_importe_loc { get; set; }
        public decimal che_estado { get; set; }
        public decimal che_nro_entrada { get; set; }
    
        public virtual agencias agencias { get; set; }
        public virtual entidades_bancarias entidades_bancarias { get; set; }
        public virtual monedas monedas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fina_movimientos_caja> fina_movimientos_caja { get; set; }
    }
}
