//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_emisores_series
    {
        public decimal ser_cod_empresa { get; set; }
        public decimal ser_cod_emisor { get; set; }
        public decimal ser_nro_serie { get; set; }
        public decimal ser_desde { get; set; }
        public decimal ser_hasta { get; set; }
        public decimal ser_ultimo { get; set; }
        public string ser_nro_timbrado { get; set; }
        public System.DateTime ser_fecha_inicio { get; set; }
        public System.DateTime ser_fecha_vto { get; set; }
        public decimal ser_nro_autorizacion { get; set; }
        public System.DateTime ser_fecha_carga { get; set; }
        public System.TimeSpan ser_hora_carga { get; set; }
        public string ser_usuario_carga { get; set; }
        public decimal ser_estado { get; set; }
        public System.DateTime ser_fecha_estado { get; set; }
        public System.TimeSpan ser_hora_estado { get; set; }
        public string ser_usuario_estado { get; set; }
        public decimal ser_nro_entrada { get; set; }
    }
}
