//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_boletas_retencion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fina_boletas_retencion()
        {
            this.fina_movimientos_caja = new HashSet<fina_movimientos_caja>();
        }
    
        public decimal bol_cod_empresa { get; set; }
        public decimal bol_clave { get; set; }
        public decimal bol_cod_sucursal { get; set; }
        public decimal bol_nro_boleta { get; set; }
        public System.DateTime bol_fecha_boleta { get; set; }
        public string bol_nombre_boleta { get; set; }
        public string bol_ruc_boleta { get; set; }
        public decimal bol_cod_moneda { get; set; }
        public decimal bol_base_afecta { get; set; }
        public decimal bol_base_afecta_loc { get; set; }
        public decimal bol_base_iva { get; set; }
        public decimal bol_base_iva_loc { get; set; }
        public decimal bol_pct_retencion { get; set; }
        public decimal bol_importe_retencion { get; set; }
        public decimal bol_importe_retencion_loc { get; set; }
        public System.DateTime bol_fecha_carga { get; set; }
        public System.TimeSpan bol_hora_carga { get; set; }
        public string bol_usuario_carga { get; set; }
        public decimal bol_nro_entrada { get; set; }
        public Nullable<System.DateTime> bol_fecha_elimina { get; set; }
        public Nullable<System.TimeSpan> bol_hora_elimina { get; set; }
        public string bol_usuario_elimina { get; set; }
        public Nullable<decimal> bol_nro_factura { get; set; }
        public decimal bol_tipo_boleta { get; set; }
        public Nullable<decimal> bol_clave_pago { get; set; }
        public Nullable<decimal> bol_cambio_retencion { get; set; }
    
        public virtual agencias agencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fina_movimientos_caja> fina_movimientos_caja { get; set; }
        public virtual monedas monedas { get; set; }
    }
}
