//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_cobranzas_modificadas
    {
        public decimal com_cod_empresa { get; set; }
        public decimal com_clave_modificacion { get; set; }
        public decimal com_clave_documento { get; set; }
        public decimal com_nro_cuota { get; set; }
        public decimal com_nro_cobro { get; set; }
        public System.DateTime com_fecha_vencimiento { get; set; }
        public decimal com_tipo_modificacion { get; set; }
        public decimal com_clave_caja { get; set; }
        public decimal com_cod_sucursal { get; set; }
        public decimal com_nro_habilitacion { get; set; }
        public decimal com_nro_habilitacion_nuevo { get; set; }
        public System.DateTime com_fecha_cobro { get; set; }
        public decimal com_tipo_transaccion { get; set; }
        public decimal com_cod_cobrador { get; set; }
        public decimal com_cod_cobrador_nuevo { get; set; }
        public decimal com_importe { get; set; }
        public decimal com_importe_loc { get; set; }
        public decimal com_cod_moneda_cobro { get; set; }
        public decimal com_cambio_cobranza { get; set; }
        public decimal com_importe_cobro { get; set; }
        public decimal com_nro_recibo { get; set; }
        public decimal com_nro_recibo_nuevo { get; set; }
        public decimal com_situacion_recibo { get; set; }
        public Nullable<decimal> com_clave_cheque { get; set; }
        public Nullable<decimal> com_clave_cheque_nuevo { get; set; }
        public System.DateTime com_fecha_carga { get; set; }
        public System.TimeSpan com_hora_carga { get; set; }
        public string com_usuario_carga { get; set; }
        public System.DateTime com_fecha_procesa { get; set; }
        public System.TimeSpan com_hora_procesa { get; set; }
        public string com_usuario_procesa { get; set; }
        public System.DateTime com_fecha_modificacion { get; set; }
        public System.TimeSpan com_hora_modificacion { get; set; }
        public string com_usuario_modificacion { get; set; }
        public decimal com_nro_entrada { get; set; }
    }
}
