//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_arqueo_caja
    {
        public decimal arq_cod_empresa { get; set; }
        public decimal arq_nro_habilitacion { get; set; }
        public decimal arq_tipo_valor { get; set; }
        public decimal arq_cod_moneda { get; set; }
        public decimal arq_importe { get; set; }
        public decimal arq_importe_loc { get; set; }
        public decimal arq_nro_entrada { get; set; }
        public Nullable<decimal> arq_saldo_deposito { get; set; }
    }
}
