//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_movimientos_caja_cobros
    {
        public decimal mcc_cod_empresa { get; set; }
        public decimal mcc_clave_caja { get; set; }
        public decimal mcc_nro_item { get; set; }
        public decimal mcc_tipo_valor { get; set; }
        public Nullable<decimal> mcc_clave_cheque { get; set; }
        public Nullable<decimal> mcc_clave_tarjeta { get; set; }
        public decimal mcc_importe_cobro { get; set; }
        public Nullable<decimal> mcc_cod_moneda { get; set; }
        public Nullable<decimal> mcc_importe_moneda { get; set; }
        public Nullable<decimal> mcc_clave_nota_credito { get; set; }
        public Nullable<decimal> mcc_clave_deposito { get; set; }
        public Nullable<decimal> mcc_importe_cobro_nc { get; set; }
    
        public virtual fina_movimientos_caja fina_movimientos_caja { get; set; }
    }
}
