//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_movimientos_caja_detalle
    {
        public decimal mcd_cod_empresa { get; set; }
        public decimal mcd_clave_caja { get; set; }
        public decimal mcd_nro_item { get; set; }
        public decimal mcd_ejercicio { get; set; }
        public string mcd_nro_cuenta { get; set; }
        public string mcd_concepto { get; set; }
        public decimal mcd_importe { get; set; }
        public decimal mcd_importe_loc { get; set; }
        public decimal mcd_nro_entrada { get; set; }
        public Nullable<decimal> mcd_clave_documento { get; set; }
    
        public virtual plan_cuentas plan_cuentas { get; set; }
    }
}
