//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_tipos_movimientos_caja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fina_tipos_movimientos_caja()
        {
            this.fina_movimientos_caja = new HashSet<fina_movimientos_caja>();
        }
    
        public decimal tmo_codigo { get; set; }
        public string tmo_descripcion { get; set; }
        public decimal tmo_tipo_movimiento { get; set; }
        public decimal tmo_nro_entrada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fina_movimientos_caja> fina_movimientos_caja { get; set; }
    }
}
