//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_emisores_documentos
    {
        public decimal emi_cod_empresa { get; set; }
        public decimal emi_codigo { get; set; }
        public string emi_nombre { get; set; }
        public decimal emi_tipo_documento { get; set; }
        public decimal emi_nro_entrada { get; set; }
    }
}
