//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_movimientos_caja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fina_movimientos_caja()
        {
            this.fina_movimientos_caja_cobros = new HashSet<fina_movimientos_caja_cobros>();
        }
    
        public decimal mca_cod_empresa { get; set; }
        public decimal mca_clave_caja { get; set; }
        public decimal mca_clave_caja_padre { get; set; }
        public decimal mca_nro_habilitacion { get; set; }
        public decimal mca_nro_movimiento { get; set; }
        public decimal mca_tipo_transaccion { get; set; }
        public decimal mca_cod_movimiento { get; set; }
        public decimal mca_cod_cobrador { get; set; }
        public System.DateTime mca_fecha { get; set; }
        public decimal mca_clave_documento { get; set; }
        public decimal mca_nro_cuota { get; set; }
        public decimal mca_nro_cobro { get; set; }
        public decimal mca_importe { get; set; }
        public decimal mca_importe_loc { get; set; }
        public decimal mca_cod_moneda_cobro { get; set; }
        public decimal mca_cambio_cobranza { get; set; }
        public decimal mca_importe_cobro { get; set; }
        public decimal mca_ingreso_neto { get; set; }
        public decimal mca_ingreso_neto_loc { get; set; }
        public decimal mca_cambio_documento { get; set; }
        public decimal mca_cambio_dia { get; set; }
        public decimal mca_tipo_valor { get; set; }
        public decimal mca_nro_recibo { get; set; }
        public string mca_concepto { get; set; }
        public Nullable<decimal> mca_clave_cheque { get; set; }
        public Nullable<decimal> mca_clave_tarjeta { get; set; }
        public Nullable<decimal> mca_clave_retencion { get; set; }
        public decimal mca_diferencia_cambio { get; set; }
        public decimal mca_estado { get; set; }
        public System.DateTime mca_fecha_carga { get; set; }
        public System.TimeSpan mca_hora_carga { get; set; }
        public string mca_usuario_carga { get; set; }
        public Nullable<decimal> mca_nro_proceso { get; set; }
        public Nullable<System.DateTime> mca_fecha_proceso { get; set; }
        public Nullable<System.TimeSpan> mca_hora_proceso { get; set; }
        public string mca_usuario_proceso { get; set; }
        public decimal mca_nro_entrada { get; set; }
        public Nullable<decimal> mca_cobro_regularizar { get; set; }
        public Nullable<System.DateTime> mca_fecha_elimina { get; set; }
        public Nullable<System.TimeSpan> mca_hora_elimina { get; set; }
        public string mca_usuario_elimina { get; set; }
        public Nullable<decimal> mca_nro_habilitacion_elimina { get; set; }
        public decimal mca_nro_asto_carga { get; set; }
    
        public virtual fina_boletas_retencion fina_boletas_retencion { get; set; }
        public virtual fina_datos_cheques fina_datos_cheques { get; set; }
        public virtual fina_datos_tarjetas fina_datos_tarjetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fina_movimientos_caja_cobros> fina_movimientos_caja_cobros { get; set; }
        public virtual fina_tipos_transacciones_cobranzas fina_tipos_transacciones_cobranzas { get; set; }
        public virtual fina_tipos_movimientos_caja fina_tipos_movimientos_caja { get; set; }
        public virtual monedas monedas { get; set; }
        public virtual fina_tipos_valores fina_tipos_valores { get; set; }
    }
}
