//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_cobros_a_regularizar
    {
        public decimal cor_cod_empresa { get; set; }
        public decimal cor_numero { get; set; }
        public System.DateTime cor_fecha { get; set; }
        public decimal cor_cod_cliente { get; set; }
        public decimal cor_clave_caja { get; set; }
        public decimal cor_cod_moneda { get; set; }
        public decimal cor_importe { get; set; }
        public decimal cor_saldo { get; set; }
        public string cor_observacion { get; set; }
        public decimal cor_nro_entrada { get; set; }
        public Nullable<decimal> cor_nro_orden { get; set; }
    }
}
