//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_tipos_operaciones_bancos
    {
        public decimal oba_codigo { get; set; }
        public string oba_descripcion { get; set; }
        public decimal oba_nro_entrada { get; set; }
    }
}
