//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_cajas_habilitaciones
    {
        public decimal hab_cod_empresa { get; set; }
        public decimal hab_nro_habilitacion { get; set; }
        public decimal hab_nro_caja { get; set; }
        public System.DateTime hab_fecha_apertura { get; set; }
        public System.TimeSpan hab_hora_apertura { get; set; }
        public string hab_usuario_apertura { get; set; }
        public decimal hab_estado { get; set; }
        public Nullable<System.DateTime> hab_fecha_cierre { get; set; }
        public Nullable<System.TimeSpan> hab_hora_cierre { get; set; }
        public string hab_usuario_cierre { get; set; }
        public decimal hab_nro_entrada { get; set; }
    }
}
