//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_tipos_cuentas_bancos
    {
        public decimal tcu_codigo { get; set; }
        public string tcu_descripcion { get; set; }
        public decimal tcu_nro_entrada { get; set; }
        public decimal tcu_cod_relacion { get; set; }
    }
}
