//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fina_cajas
    {
        public decimal caj_cod_empresa { get; set; }
        public decimal caj_nro_caja { get; set; }
        public string caj_nombre { get; set; }
        public decimal caj_cod_sucursal { get; set; }
        public string caj_usuario_encargado { get; set; }
        public decimal caj_nro_entrada { get; set; }
    
        public virtual agencias agencias { get; set; }
    }
}
