//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class flujo_efectivo
    {
        public decimal cod_empresa { get; set; }
        public decimal ejercicio { get; set; }
        public string codigo { get; set; }
        public decimal monto { get; set; }
        public decimal resultado_final { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string usuario { get; set; }
    }
}
