//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fondo_fijo_transferencias
    {
        public decimal cod_empresa { get; set; }
        public decimal nro_transferencia { get; set; }
        public decimal nro_caja { get; set; }
        public string nro_referencia_origen { get; set; }
        public string nro_referencia_destino { get; set; }
        public decimal cod_money { get; set; }
        public decimal importe { get; set; }
        public string observacion { get; set; }
        public string usuario_carga { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public string hora_carga { get; set; }
    
        public virtual cajas_fondo_fijo cajas_fondo_fijo { get; set; }
    }
}
