//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fondo_fijo
    {
        public decimal cod_empresa { get; set; }
        public decimal nro_caja { get; set; }
        public decimal operacion { get; set; }
        public decimal nro_entrada { get; set; }
        public decimal nro_reposicion { get; set; }
        public Nullable<System.DateTime> fecha_reposicion { get; set; }
        public string hora_reposicion { get; set; }
        public string usuario_reposicion { get; set; }
        public Nullable<decimal> nro_orden_pago { get; set; }
        public decimal cod_moneda_caja { get; set; }
        public decimal monto_fijo_caja { get; set; }
    
        public virtual facturas_cab facturas_cab { get; set; }
    }
}
