//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class fondo_fijo_cabeza
    {
        public decimal cod_empresa { get; set; }
        public decimal nro_caja { get; set; }
        public decimal item { get; set; }
        public string nro_referencia { get; set; }
        public decimal cod_moneda { get; set; }
        public decimal t_cambio { get; set; }
        public decimal importe { get; set; }
        public decimal nro_entrada_fact { get; set; }
        public decimal transferencias { get; set; }
        public decimal saldo { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public string hora_carga { get; set; }
        public string usuario_carga { get; set; }
        public decimal estado { get; set; }
        public Nullable<System.DateTime> fecha_finiquito { get; set; }
        public string hora_finiquito { get; set; }
        public string usuario_finiquito { get; set; }
    
        public virtual cajas_fondo_fijo cajas_fondo_fijo { get; set; }
    }
}
