//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class geometry_columns
    {
        public string f_table_catalog { get; set; }
        public string f_table_schema { get; set; }
        public string f_table_name { get; set; }
        public string f_geometry_column { get; set; }
        public int coord_dimension { get; set; }
        public int srid { get; set; }
        public string type { get; set; }
    }
}
