//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingresos_det
    {
        public decimal cod_empresa { get; set; }
        public decimal nro_ingreso { get; set; }
        public decimal item { get; set; }
        public decimal nro_entrada_cac { get; set; }
        public decimal nro_pago { get; set; }
        public decimal ejercicio { get; set; }
        public string cta_contable { get; set; }
        public string concepto { get; set; }
        public decimal importe { get; set; }
        public decimal importe_gs { get; set; }
        public decimal fluctuacion { get; set; }
        public Nullable<decimal> importe_cobro { get; set; }
        public decimal nro_cuota { get; set; }
    
        public virtual ingresos_cab ingresos_cab { get; set; }
    }
}
