//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingresos_cab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ingresos_cab()
        {
            this.ingresos_det = new HashSet<ingresos_det>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal nro_ingreso { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal tipo_ingreso { get; set; }
        public decimal nro_recibo { get; set; }
        public Nullable<decimal> cod_moneda { get; set; }
        public decimal t_cambio { get; set; }
        public decimal importe { get; set; }
        public decimal importe_gs { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public string hora_carga { get; set; }
        public string usuario_carga { get; set; }
        public decimal nro_asto_carga { get; set; }
        public decimal estado { get; set; }
        public Nullable<System.DateTime> fecha_procesa { get; set; }
        public string hora_procesa { get; set; }
        public string usuario_procesa { get; set; }
        public Nullable<System.DateTime> fecha_anula { get; set; }
        public string hora_anula { get; set; }
        public string usuario_anula { get; set; }
        public decimal nro_asto_anula { get; set; }
        public decimal cod_agcia { get; set; }
        public decimal nro_lote { get; set; }
        public Nullable<System.DateTime> fecha_lote { get; set; }
        public string hora_lote { get; set; }
        public string usuario_lote { get; set; }
        public Nullable<System.DateTime> fecha_recibe { get; set; }
        public string hora_recibe { get; set; }
        public string usuario_recibe { get; set; }
        public decimal nro_ingreso_agcia { get; set; }
        public Nullable<decimal> origen { get; set; }
    
        public virtual tipos_ingresos tipos_ingresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingresos_det> ingresos_det { get; set; }
        public virtual monedas monedas { get; set; }
    }
}
