//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingresos_valores
    {
        public Nullable<decimal> cod_empresa { get; set; }
        public decimal nro_ingreso { get; set; }
        public decimal nro_item { get; set; }
        public decimal cod_tipo { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<System.DateTime> fecha_cheque { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public string titular { get; set; }
        public Nullable<System.DateTime> fecha_descarga { get; set; }
        public string usuario_descarga { get; set; }
        public Nullable<decimal> nro_cheque { get; set; }
        public Nullable<decimal> clave_documento_nc { get; set; }
        public string cta_banco { get; set; }
        public Nullable<decimal> cod_entidad { get; set; }
        public string nro_retencion { get; set; }
        public Nullable<System.DateTime> fecha_retencion { get; set; }
    }
}
