//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_inicial
    {
        public decimal cod_deposito { get; set; }
        public string codigo_barras { get; set; }
        public Nullable<decimal> existencia { get; set; }
        public Nullable<decimal> costo { get; set; }
    }
}
