//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class liquidacion
    {
        public string cod_empresa { get; set; }
        public decimal anho { get; set; }
        public string coddespachante { get; set; }
        public decimal nrodespacho { get; set; }
        public decimal linea { get; set; }
        public string codarancel { get; set; }
        public string codprov { get; set; }
        public string cod_tp_comp { get; set; }
        public System.DateTimeOffset fechacbte { get; set; }
        public decimal nrocbte { get; set; }
        public string af_costos { get; set; }
        public decimal exento { get; set; }
        public decimal gravado { get; set; }
        public decimal iva { get; set; }
        public string codplancta { get; set; }
        public string codplanaux { get; set; }
        public string concepto { get; set; }
        public string libroiva { get; set; }
        public string periodo { get; set; }
        public string timbrado { get; set; }
        public string af_valorimponible { get; set; }
        public decimal totalaplicado { get; set; }
        public string tipo_iva { get; set; }
        public string codinciso { get; set; }
        public string cod_tp_comp_ret { get; set; }
        public Nullable<decimal> nro_retencion { get; set; }
        public Nullable<System.DateTime> fecha_retencion { get; set; }
        public Nullable<decimal> monto_retencion { get; set; }
        public Nullable<decimal> porc_iva { get; set; }
        public string timbrado_ret { get; set; }
    }
}
