//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class matriz_cabeza
    {
        public decimal nro_matriz { get; set; }
        public decimal cod_persona { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public string usuario_genera { get; set; }
        public string hora_genera { get; set; }
        public Nullable<System.DateTime> fecha_genera { get; set; }
    }
}
