//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class matriz_detalle
    {
        public decimal nro_matriz { get; set; }
        public decimal item { get; set; }
        public decimal cod_articulo { get; set; }
        public string codigo_barras { get; set; }
        public string nombre { get; set; }
        public decimal precio_venta { get; set; }
        public decimal stock_actual { get; set; }
        public decimal pct_iva { get; set; }
        public decimal costo_gs { get; set; }
        public decimal cant_ult_pedido { get; set; }
        public Nullable<System.DateTime> fecha_ult_compra { get; set; }
        public Nullable<decimal> cantidad_venta_8 { get; set; }
        public Nullable<System.DateTime> fecha_ult_venta { get; set; }
        public Nullable<decimal> cantidad_venta_ult_ped { get; set; }
    }
}
