//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensajes
    {
        public string linea1 { get; set; }
        public string linea2 { get; set; }
        public string linea3 { get; set; }
        public string linea4 { get; set; }
        public string linea5 { get; set; }
        public string linea6 { get; set; }
        public string linea7 { get; set; }
        public string linea8 { get; set; }
        public string linea9 { get; set; }
        public string linea10 { get; set; }
        public string linea11 { get; set; }
        public string linea12 { get; set; }
        public string linea13 { get; set; }
        public string linea14 { get; set; }
        public string linea15 { get; set; }
        public string linea_ticket1 { get; set; }
        public string linea_ticket2 { get; set; }
        public string linea_ticket3 { get; set; }
        public string linea_ticket4 { get; set; }
        public string linea_ticket5 { get; set; }
        public string linea_ticket6 { get; set; }
        public string linea_ticket7 { get; set; }
    }
}
