//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class monedas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public monedas()
        {
            this.cajas_fondo_fijo = new HashSet<cajas_fondo_fijo>();
            this.cotizaciones = new HashSet<cotizaciones>();
            this.facturas_cab = new HashSet<facturas_cab>();
            this.fina_boletas_retencion = new HashSet<fina_boletas_retencion>();
            this.fina_datos_cheques = new HashSet<fina_datos_cheques>();
            this.fina_datos_tarjetas = new HashSet<fina_datos_tarjetas>();
            this.fina_movimientos_caja = new HashSet<fina_movimientos_caja>();
            this.ingresos_cab = new HashSet<ingresos_cab>();
        }
    
        public decimal cod_moneda { get; set; }
        public string descripcion { get; set; }
        public string simbolo { get; set; }
        public decimal nro_entrada { get; set; }
        public string usuario { get; set; }
        public decimal cant_decimales { get; set; }
        public string mon_iso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas_fondo_fijo> cajas_fondo_fijo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizaciones> cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturas_cab> facturas_cab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fina_boletas_retencion> fina_boletas_retencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fina_datos_cheques> fina_datos_cheques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fina_datos_tarjetas> fina_datos_tarjetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fina_movimientos_caja> fina_movimientos_caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingresos_cab> ingresos_cab { get; set; }
    }
}
