//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class motivos_ajustes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public motivos_ajustes()
        {
            this.ajustes_cab = new HashSet<ajustes_cab>();
        }
    
        public decimal cod_motivo { get; set; }
        public string descripcion { get; set; }
        public string usuario { get; set; }
        public decimal nro_entrada { get; set; }
        public string cta_contable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ajustes_cab> ajustes_cab { get; set; }
    }
}
