//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento_articulos_temp_det
    {
        public decimal cod_empresa { get; set; }
        public decimal nro_movimiento { get; set; }
        public decimal item { get; set; }
        public decimal cod_articulo { get; set; }
        public decimal cantidad { get; set; }
        public decimal imponible { get; set; }
        public decimal iva { get; set; }
        public decimal exento { get; set; }
        public decimal otros { get; set; }
        public decimal total { get; set; }
        public decimal descuento { get; set; }
        public decimal neto { get; set; }
        public decimal flete { get; set; }
        public decimal imponible_gs { get; set; }
        public decimal iva_gs { get; set; }
        public decimal exento_gs { get; set; }
        public decimal otros_gs { get; set; }
        public decimal total_gs { get; set; }
        public decimal descuento_gs { get; set; }
        public decimal neto_gs { get; set; }
        public decimal flete_gs { get; set; }
        public decimal pct_iva { get; set; }
        public Nullable<decimal> cod_bien { get; set; }
        public decimal costo { get; set; }
        public decimal costo_gs { get; set; }
        public decimal cod_deposito { get; set; }
        public Nullable<decimal> cod_centro { get; set; }
        public decimal cod_area { get; set; }
        public decimal precio_unitario { get; set; }
        public decimal precio_unitario_gs { get; set; }
        public decimal marca_flete { get; set; }
        public Nullable<decimal> nro_entrada_fact { get; set; }
    
        public virtual movimiento_articulos_temp_cab movimiento_articulos_temp_cab { get; set; }
    }
}
