//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento_articulos_temp_cuota
    {
        public decimal cod_empresa { get; set; }
        public decimal nro_movimiento { get; set; }
        public decimal nro_cuota { get; set; }
        public System.DateTime fecha_vto { get; set; }
        public decimal importe { get; set; }
        public decimal importe_gs { get; set; }
    
        public virtual movimiento_articulos_temp_cab movimiento_articulos_temp_cab { get; set; }
    }
}
