//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento_articulos_temp_cab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movimiento_articulos_temp_cab()
        {
            this.movimiento_articulos_temp_det = new HashSet<movimiento_articulos_temp_det>();
            this.movimiento_articulos_temp_cuota = new HashSet<movimiento_articulos_temp_cuota>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal nro_movimiento { get; set; }
        public decimal nro_entrada_fact { get; set; }
        public decimal tipo_factura { get; set; }
        public string nro_comprobante { get; set; }
        public decimal cod_rubro { get; set; }
        public decimal fondo_fijo { get; set; }
        public Nullable<decimal> nro_caja { get; set; }
        public decimal cod_operacion { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string usuario { get; set; }
        public decimal cod_agcia { get; set; }
        public decimal nro_pedido { get; set; }
        public decimal cod_persona { get; set; }
        public string nro_timbrado { get; set; }
        public decimal cod_moneda { get; set; }
        public decimal t_cambio { get; set; }
        public decimal imponible { get; set; }
        public decimal imponible10 { get; set; }
        public decimal imponible5 { get; set; }
        public decimal iva { get; set; }
        public decimal iva10 { get; set; }
        public decimal iva5 { get; set; }
        public decimal exento { get; set; }
        public decimal otros { get; set; }
        public decimal total { get; set; }
        public decimal descuento { get; set; }
        public decimal neto { get; set; }
        public decimal imponible_gs { get; set; }
        public decimal imponible10_gs { get; set; }
        public decimal imponible5_gs { get; set; }
        public decimal iva_gs { get; set; }
        public decimal iva10_gs { get; set; }
        public decimal iva5_gs { get; set; }
        public decimal exento_gs { get; set; }
        public decimal otros_gs { get; set; }
        public decimal total_gs { get; set; }
        public decimal descuento_gs { get; set; }
        public decimal neto_gs { get; set; }
        public string observacion { get; set; }
        public decimal estado { get; set; }
        public Nullable<System.DateTime> fecha_autorizo { get; set; }
        public string hora_autorizo { get; set; }
        public string usuario_autorizo { get; set; }
        public Nullable<System.DateTime> fecha_realizacion { get; set; }
        public string hora_realizacion { get; set; }
        public string usuario_realizacion { get; set; }
        public Nullable<decimal> cod_camion { get; set; }
        public Nullable<System.DateTime> fecha_remision_salida { get; set; }
        public Nullable<System.DateTime> fecha_remision_entrega { get; set; }
        public Nullable<decimal> cod_transportista { get; set; }
        public Nullable<decimal> cod_chofer { get; set; }
        public Nullable<System.DateTime> fecha_descarga { get; set; }
        public string hora_descarga { get; set; }
        public string usuario_descarga { get; set; }
        public Nullable<System.DateTime> fecha_elimina { get; set; }
        public string hora_elimina { get; set; }
        public string usuario_elimina { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<decimal> clave_orden { get; set; }
        public Nullable<System.DateTime> fecha_impresion { get; set; }
        public string usuario_impresion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_articulos_temp_det> movimiento_articulos_temp_det { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_articulos_temp_cuota> movimiento_articulos_temp_cuota { get; set; }
    }
}
