//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class niveles
    {
        public decimal cod_empresa { get; set; }
        public decimal ejercicio { get; set; }
        public decimal registro { get; set; }
        public decimal niv1 { get; set; }
        public decimal niv2 { get; set; }
        public decimal niv3 { get; set; }
        public decimal niv4 { get; set; }
        public decimal niv5 { get; set; }
        public decimal niv6 { get; set; }
        public decimal niv7 { get; set; }
        public decimal niv8 { get; set; }
        public string usuario { get; set; }
        public decimal nro_entrada { get; set; }
    
        public virtual periodos_fiscales periodos_fiscales { get; set; }
    }
}
