//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class operaciones_bancarias_cab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public operaciones_bancarias_cab()
        {
            this.operaciones_bancarias_det = new HashSet<operaciones_bancarias_det>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal tipo_operacion { get; set; }
        public decimal nro_movimiento { get; set; }
        public decimal ejercicio { get; set; }
        public string cta_contable { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal cod_moneda { get; set; }
        public decimal t_cambio { get; set; }
        public decimal total { get; set; }
        public decimal total_me { get; set; }
        public decimal nro_asto { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public string hora_carga { get; set; }
        public string usuario_carga { get; set; }
        public Nullable<System.DateTime> fecha_elimina { get; set; }
        public string hora_elimina { get; set; }
        public string usuario_elimina { get; set; }
        public decimal nro_asto_elimina { get; set; }
        public decimal cod_agcia { get; set; }
        public decimal nro_lote { get; set; }
        public Nullable<System.DateTime> fecha_lote { get; set; }
        public string hora_lote { get; set; }
        public string usuario_lote { get; set; }
        public Nullable<System.DateTime> fecha_recibe { get; set; }
        public string hora_recibe { get; set; }
        public string usuario_recibe { get; set; }
        public decimal nro_movimiento_agcia { get; set; }
        public Nullable<System.DateTime> fecha_recaudacion { get; set; }
        public Nullable<decimal> nro_caja { get; set; }
        public Nullable<decimal> nro_habilitacion { get; set; }
    
        public virtual tipos_operaciones_bancos tipos_operaciones_bancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operaciones_bancarias_det> operaciones_bancarias_det { get; set; }
    }
}
