//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class operaciones_bancarias_det
    {
        public decimal cod_empresa { get; set; }
        public decimal tipo_operacion { get; set; }
        public decimal nro_movimiento { get; set; }
        public decimal item { get; set; }
        public string cta_contable { get; set; }
        public string concepto { get; set; }
        public decimal importe { get; set; }
        public decimal importe_me { get; set; }
        public string nro_comprobante { get; set; }
        public Nullable<decimal> tipo_valor { get; set; }
    
        public virtual operaciones_bancarias_cab operaciones_bancarias_cab { get; set; }
    }
}
