//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_pago_cabeza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orden_pago_cabeza()
        {
            this.orden_pago_cheques = new HashSet<orden_pago_cheques>();
            this.orden_pago_facturas = new HashSet<orden_pago_facturas>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal nro_orden { get; set; }
        public Nullable<decimal> ejercicio { get; set; }
        public string cta_contable { get; set; }
        public decimal cod_money { get; set; }
        public decimal t_cambio { get; set; }
        public decimal total { get; set; }
        public decimal total_retencion { get; set; }
        public decimal tipo_orden { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public string hora_carga { get; set; }
        public string usuario_carga { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public string hora_pago { get; set; }
        public string usuario_pago { get; set; }
        public Nullable<System.DateTime> fecha_anula { get; set; }
        public string hora_anul { get; set; }
        public string usuario_anula { get; set; }
        public Nullable<System.DateTime> fecha_autoriza { get; set; }
        public string hora_autoriza { get; set; }
        public string usuario_autoriza { get; set; }
        public Nullable<System.DateTime> fecha_imprime { get; set; }
        public string hora_impresion { get; set; }
        public decimal nro_entrada { get; set; }
        public decimal nro_recibo { get; set; }
        public Nullable<decimal> tipo_pago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_pago_cheques> orden_pago_cheques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_pago_facturas> orden_pago_facturas { get; set; }
        public virtual plan_cuentas plan_cuentas { get; set; }
    }
}
