//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_pago_impresion
    {
        public decimal nro_transaccion { get; set; }
        public decimal item { get; set; }
        public decimal cod_empresa { get; set; }
        public decimal nro_orden { get; set; }
        public string nombre_persona { get; set; }
        public string tipo_documento { get; set; }
        public string documento_persona { get; set; }
        public decimal cod_money { get; set; }
        public string descripcion_moneda { get; set; }
        public string simbolo_moneda { get; set; }
        public decimal t_cambio { get; set; }
        public decimal total_cheques { get; set; }
        public decimal total_retencion { get; set; }
        public decimal total_orden { get; set; }
        public decimal cant_cheques { get; set; }
        public string cta_contable { get; set; }
        public string nombre_cuenta { get; set; }
        public string concepto { get; set; }
        public decimal debito { get; set; }
        public decimal credito { get; set; }
        public decimal nro_retencion { get; set; }
        public System.DateTime fecha_orden { get; set; }
        public Nullable<System.DateTime> fecha_autorizo { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<System.DateTime> fecha_anul { get; set; }
        public string hora_carga { get; set; }
        public string hora_autorizo { get; set; }
        public string hora_imprime { get; set; }
        public string hora_anula { get; set; }
        public string usuario_carga { get; set; }
        public string usuario_autoriza { get; set; }
        public string usuario_imprime { get; set; }
        public string usuario_anula { get; set; }
        public Nullable<System.DateTime> fecha_fact { get; set; }
    }
}
