//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_compra_detalle
    {
        public decimal cod_empresa { get; set; }
        public decimal nro_orden { get; set; }
        public decimal item { get; set; }
        public decimal cod_centro { get; set; }
        public string articulo { get; set; }
        public decimal cod_unidad { get; set; }
        public decimal cantidad { get; set; }
        public decimal costo_unitario { get; set; }
        public decimal costo_total { get; set; }
    }
}
