//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_pago_facturas
    {
        public decimal cod_empresa { get; set; }
        public decimal nro_orden { get; set; }
        public decimal nro_entrada_fact { get; set; }
        public decimal importe { get; set; }
        public decimal importe_gs { get; set; }
        public decimal fluctuacion { get; set; }
        public decimal nro_cuota { get; set; }
        public Nullable<decimal> monto_retencion { get; set; }
    
        public virtual orden_pago_cabeza orden_pago_cabeza { get; set; }
    }
}
