//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_pago_cheques
    {
        public decimal cod_empresa { get; set; }
        public decimal nro_orden { get; set; }
        public decimal item { get; set; }
        public decimal nro_cheque { get; set; }
        public decimal importe_cheque { get; set; }
        public decimal importe_cheque_gs { get; set; }
        public decimal importe_retencion { get; set; }
        public decimal importe_factura { get; set; }
        public decimal importe_factura_gs { get; set; }
        public decimal importe_fluctuacion { get; set; }
        public string nombre_cheque { get; set; }
        public Nullable<System.DateTime> fecha_cheque { get; set; }
        public string hora_cheque { get; set; }
        public string usuario_cheque { get; set; }
        public Nullable<System.DateTime> fecha_anula { get; set; }
        public string hora_anula { get; set; }
        public string usuario_anula { get; set; }
        public Nullable<decimal> nro_entrega { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public string hora_entrega { get; set; }
        public string usuario_entrega { get; set; }
        public string persona_retira { get; set; }
        public string documento { get; set; }
        public string nro_recibo { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
    
        public virtual orden_pago_cabeza orden_pago_cabeza { get; set; }
    }
}
