//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_compra_cabeza
    {
        public decimal cod_empresa { get; set; }
        public decimal nro_orden { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal cod_persona { get; set; }
        public decimal cod_moneda { get; set; }
        public decimal total { get; set; }
        public string solicitante { get; set; }
        public string observacion { get; set; }
        public string autorizado_por { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public string hora_carga { get; set; }
        public string usuario_carga { get; set; }
        public Nullable<System.DateTime> fecha_imprime { get; set; }
        public string hora_imprime { get; set; }
        public string usuario_imprime { get; set; }
        public Nullable<System.DateTime> fecha_anula { get; set; }
        public string hora_anula { get; set; }
        public string usuario_anula { get; set; }
        public decimal nro_entrada { get; set; }
    }
}
