//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas_frentes
    {
        public decimal cod_empresa { get; set; }
        public decimal cod_persona { get; set; }
        public decimal cod_frente { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> cod_zona { get; set; }
        public string observacion { get; set; }
        public string nombre { get; set; }
        public string documento { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
    }
}
