//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas_puntos
    {
        public decimal cod_empresa { get; set; }
        public decimal cod_persona { get; set; }
        public decimal nro_caja { get; set; }
        public decimal nro_habilitacion { get; set; }
        public decimal nro_mvto { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public decimal debito { get; set; }
        public decimal credito { get; set; }
        public decimal item { get; set; }
        public Nullable<decimal> cod_articulo { get; set; }
    }
}
