//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas_timbrado
    {
        public decimal cod_empresa { get; set; }
        public decimal cod_persona { get; set; }
        public decimal tipo { get; set; }
        public decimal cod_establecimiento { get; set; }
        public decimal cod_emision { get; set; }
        public string nro_timbrado { get; set; }
        public System.DateTime inicio_vigencia { get; set; }
        public Nullable<System.DateTime> vencimiento { get; set; }
        public string usuario { get; set; }
        public Nullable<decimal> nro_entrada { get; set; }
        public Nullable<decimal> desde { get; set; }
        public Nullable<decimal> hasta { get; set; }
    }
}
