//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas_app
    {
        public decimal cod_empresa { get; set; }
        public decimal cod_persona { get; set; }
        public string nombre { get; set; }
        public string usuario_app { get; set; }
        public Nullable<decimal> tipo_usuario { get; set; }
        public Nullable<decimal> cod_establecimiento { get; set; }
        public Nullable<decimal> cod_emision { get; set; }
        public Nullable<decimal> estado { get; set; }
    }
}
