//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_cuentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plan_cuentas()
        {
            this.borrador = new HashSet<borrador>();
            this.fina_movimientos_caja_detalle = new HashSet<fina_movimientos_caja_detalle>();
            this.libro_diario = new HashSet<libro_diario>();
            this.orden_pago_cabeza = new HashSet<orden_pago_cabeza>();
            this.presupuesto_cuentas = new HashSet<presupuesto_cuentas>();
            this.revaluo_cabeza = new HashSet<revaluo_cabeza>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal ejercicio { get; set; }
        public string cta_contable { get; set; }
        public string nombre_cuenta { get; set; }
        public string nombre_corto { get; set; }
        public decimal cod_moneda { get; set; }
        public decimal nivel { get; set; }
        public string imputable { get; set; }
        public string libro_banco { get; set; }
        public string revaluo { get; set; }
        public decimal nro_entrada { get; set; }
        public string usuario { get; set; }
        public decimal duplica { get; set; }
    
        public virtual bancos bancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrador> borrador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fina_movimientos_caja_detalle> fina_movimientos_caja_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libro_diario> libro_diario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_pago_cabeza> orden_pago_cabeza { get; set; }
        public virtual periodos_fiscales periodos_fiscales { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<presupuesto_cuentas> presupuesto_cuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<revaluo_cabeza> revaluo_cabeza { get; set; }
    }
}
