//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class politicas_de_venta
    {
        public decimal cod_empresa { get; set; }
        public decimal tipo_politica { get; set; }
        public decimal cod_articulo { get; set; }
        public decimal cod_moneda { get; set; }
        public decimal precio_unitario { get; set; }
    
        public virtual articulos articulos { get; set; }
        public virtual tipos_politicas_venta tipos_politicas_venta { get; set; }
    }
}
