//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_informe
    {
        public decimal nro_transaccion { get; set; }
        public decimal cod_empresa { get; set; }
        public decimal ejercicio { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public decimal nivel { get; set; }
        public decimal ultimo { get; set; }
        public decimal p_enero { get; set; }
        public decimal e_enero { get; set; }
        public decimal p_febrero { get; set; }
        public decimal e_febrero { get; set; }
        public decimal p_marzo { get; set; }
        public decimal e_marzo { get; set; }
        public decimal p_abril { get; set; }
        public decimal e_abril { get; set; }
        public decimal p_mayo { get; set; }
        public decimal e_mayo { get; set; }
        public decimal p_junio { get; set; }
        public decimal e_junio { get; set; }
        public decimal p_julio { get; set; }
        public decimal e_julio { get; set; }
        public decimal p_agosto { get; set; }
        public decimal e_agosto { get; set; }
        public decimal p_setiembre { get; set; }
        public decimal e_setiembre { get; set; }
        public decimal p_octubre { get; set; }
        public decimal e_octubre { get; set; }
        public decimal p_noviembre { get; set; }
        public decimal e_noviembre { get; set; }
        public decimal p_diciembre { get; set; }
        public decimal e_diciembre { get; set; }
    }
}
