//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_cuentas
    {
        public decimal cod_empresa { get; set; }
        public decimal ejercicio { get; set; }
        public string codigo { get; set; }
        public string cta_contable { get; set; }
        public decimal suma { get; set; }
        public string usuario_carga { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public string hora_carga { get; set; }
    
        public virtual plan_cuentas plan_cuentas { get; set; }
        public virtual presupuesto_items presupuesto_items { get; set; }
    }
}
