//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public presupuesto_items()
        {
            this.presupuesto_cuentas = new HashSet<presupuesto_cuentas>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal ejercicio { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public decimal tipo_item { get; set; }
        public decimal nivel { get; set; }
        public decimal ultimo { get; set; }
        public decimal estado { get; set; }
        public string usuario_carga { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public string hora_carga { get; set; }
        public string usuario_modifica { get; set; }
        public System.DateTime fecha_modifica { get; set; }
        public string hora_modifica { get; set; }
        public decimal nro_entrada { get; set; }
    
        public virtual empresas empresas { get; set; }
        public virtual presupuesto presupuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<presupuesto_cuentas> presupuesto_cuentas { get; set; }
    }
}
