//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto
    {
        public decimal cod_empresa { get; set; }
        public decimal ejercicio { get; set; }
        public string codigo { get; set; }
        public decimal enero { get; set; }
        public decimal febrero { get; set; }
        public decimal marzo { get; set; }
        public decimal abril { get; set; }
        public decimal mayo { get; set; }
        public decimal junio { get; set; }
        public decimal julio { get; set; }
        public decimal agosto { get; set; }
        public decimal setiembre { get; set; }
        public decimal octubre { get; set; }
        public decimal noviembre { get; set; }
        public decimal diciembre { get; set; }
        public string usuario_carga { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public string hora_carga { get; set; }
        public string usuario_modifica { get; set; }
        public System.DateTime fecha_modifica { get; set; }
        public string hora_modifica { get; set; }
        public decimal nro_entrada { get; set; }
    
        public virtual presupuesto_items presupuesto_items { get; set; }
    }
}
