//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class revaluo_detalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public revaluo_detalle()
        {
            this.revaluo_movimientos = new HashSet<revaluo_movimientos>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal cod_inventario { get; set; }
        public decimal item { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_compra { get; set; }
        public decimal costo { get; set; }
        public decimal ano_vida { get; set; }
        public decimal nro_entrada_factura { get; set; }
        public decimal item_factura { get; set; }
        public decimal nro_entrada { get; set; }
        public string usuario { get; set; }
    
        public virtual revaluo_cabeza revaluo_cabeza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<revaluo_movimientos> revaluo_movimientos { get; set; }
    }
}
