//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class revaluo_cabeza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public revaluo_cabeza()
        {
            this.revaluo_detalle = new HashSet<revaluo_detalle>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal cod_inventario { get; set; }
        public decimal ejercicio { get; set; }
        public string cta_contable { get; set; }
        public string nombre { get; set; }
        public decimal revaluo { get; set; }
        public decimal depreciacion { get; set; }
        public string usuario { get; set; }
        public decimal nro_entrada { get; set; }
    
        public virtual plan_cuentas plan_cuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<revaluo_detalle> revaluo_detalle { get; set; }
    }
}
