//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_tipos_justificativos
    {
        public decimal tju_codigo { get; set; }
        public string tju_descripcion { get; set; }
        public Nullable<decimal> tju_nro_entrada { get; set; }
    }
}
