//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_ciudades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rrhh_ciudades()
        {
            this.rrhh_sucursales = new HashSet<rrhh_sucursales>();
        }
    
        public decimal ciu_cod_empresa { get; set; }
        public decimal ciu_cod_ciudad { get; set; }
        public decimal ciu_cod_pais { get; set; }
        public decimal ciu_cod_dpto { get; set; }
        public string ciu_nombre { get; set; }
        public decimal ciu_nro_entrada { get; set; }
        public string ciu_usuario { get; set; }
    
        public virtual rrhh_departamentos rrhh_departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_sucursales> rrhh_sucursales { get; set; }
    }
}
