//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_solicitud_vacaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rrhh_solicitud_vacaciones()
        {
            this.rrhh_vacaciones = new HashSet<rrhh_vacaciones>();
        }
    
        public decimal sol_cod_empresa { get; set; }
        public decimal sol_nro_solicitud { get; set; }
        public System.DateTime sol_fecha_solicitud { get; set; }
        public decimal sol_cod_empleado { get; set; }
        public decimal sol_antiguedad_actual { get; set; }
        public decimal sol_cant_dias_disponible { get; set; }
        public System.DateTime sol_fecha_desde { get; set; }
        public System.DateTime sol_fecha_hasta { get; set; }
        public decimal sol_cant_dias_solicitado { get; set; }
        public string sol_observacion { get; set; }
        public decimal sol_estado { get; set; }
        public string sol_usuario_estado { get; set; }
        public string sol_observacion_estado { get; set; }
        public decimal sol_nro_entrada { get; set; }
        public string sol_usuario { get; set; }
    
        public virtual rrhh_empleados rrhh_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_vacaciones> rrhh_vacaciones { get; set; }
    }
}
