//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_departamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rrhh_departamentos()
        {
            this.rrhh_ciudades = new HashSet<rrhh_ciudades>();
        }
    
        public decimal dep_cod_empresa { get; set; }
        public decimal dep_cod_pais { get; set; }
        public decimal dep_codigo { get; set; }
        public string dep_nombre { get; set; }
        public decimal dep_nro_entrada { get; set; }
        public string dep_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_ciudades> rrhh_ciudades { get; set; }
        public virtual rrhh_paises rrhh_paises { get; set; }
    }
}
