//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_marcaciones
    {
        public decimal mar_cod_empresa { get; set; }
        public decimal mar_cod_empleado { get; set; }
        public System.DateTime mar_fecha { get; set; }
        public System.TimeSpan mar_hora_entrada1 { get; set; }
        public Nullable<System.TimeSpan> mar_hora_entrada2 { get; set; }
        public Nullable<System.TimeSpan> mar_hora_entrada3 { get; set; }
        public Nullable<System.TimeSpan> mar_hora_salida_1 { get; set; }
        public Nullable<System.TimeSpan> mar_hora_salida_2 { get; set; }
        public Nullable<System.TimeSpan> mar_hora_salida_3 { get; set; }
        public decimal mar_minutos_tarde1 { get; set; }
        public decimal mar_minutos_tarde2 { get; set; }
        public decimal mar_minutos_tarde3 { get; set; }
        public decimal mar_tolerancia1 { get; set; }
        public decimal mar_tolerancia2 { get; set; }
        public decimal mar_tolerancia3 { get; set; }
        public decimal mar_descontar1 { get; set; }
        public decimal mar_descontar2 { get; set; }
        public decimal mar_descontar3 { get; set; }
        public decimal mar_ausencia { get; set; }
        public decimal mar_justificado { get; set; }
        public string mar_observacion { get; set; }
        public decimal mar_total_descontar { get; set; }
        public decimal mar_importe_por_minuto { get; set; }
        public decimal mar_importe_total_descuento { get; set; }
        public System.DateTime mar_fecha_generacion { get; set; }
        public System.TimeSpan mar_hora_generacion { get; set; }
        public string mar_login_generacion { get; set; }
        public decimal mar_estado { get; set; }
        public Nullable<System.DateTime> mar_fecha_proceso { get; set; }
        public Nullable<System.TimeSpan> mar_hora_proceso { get; set; }
        public string mar_login_proceso { get; set; }
        public decimal mar_nro_entrada { get; set; }
        public string mar_usuario { get; set; }
        public Nullable<decimal> mar_tipo_ausencia { get; set; }
        public Nullable<decimal> mar_motivo_ausencia { get; set; }
    
        public virtual rrhh_empleados rrhh_empleados { get; set; }
    }
}
