//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_trabajos_anteriores
    {
        public decimal tra_cod_empresa { get; set; }
        public decimal tra_cod_empleado { get; set; }
        public decimal tra_item { get; set; }
        public string tra_empresa { get; set; }
        public string tra_telefono_empresa { get; set; }
        public string tra_referencia { get; set; }
        public string tra_telefono_referencia { get; set; }
        public string tra_cargo { get; set; }
        public System.DateTime tra_desde { get; set; }
        public System.DateTime tra_hasta { get; set; }
        public string tra_motivo_salida { get; set; }
        public decimal tra_ultimo_sueldo { get; set; }
        public string tra_observaciones { get; set; }
        public decimal tra_nro_entrada { get; set; }
        public string tra_usuario { get; set; }
    
        public virtual rrhh_empleados rrhh_empleados { get; set; }
    }
}
