//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_motivos_ausencia
    {
        public decimal moa_cod_empresa { get; set; }
        public decimal moa_codigo { get; set; }
        public string moa_descripcion { get; set; }
        public decimal moa_nro_entrada { get; set; }
        public string moa_usuario { get; set; }
    }
}
