//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_tipos_estudios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rrhh_tipos_estudios()
        {
            this.rrhh_estudios = new HashSet<rrhh_estudios>();
        }
    
        public decimal tes_cod_empresa { get; set; }
        public decimal tes_codigo { get; set; }
        public string tes_descripcion { get; set; }
        public decimal tes_nro_entrada { get; set; }
        public string tes_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_estudios> rrhh_estudios { get; set; }
    }
}
