//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_registro_marcaciones
    {
        public decimal mar_codigo { get; set; }
        public decimal mar_nro_marcacion { get; set; }
        public System.DateTime mar_fecha { get; set; }
        public System.TimeSpan mar_hora { get; set; }
        public decimal mar_cod_reloj { get; set; }
        public string mar_tipo { get; set; }
    }
}
