//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_historico_situaciones
    {
        public decimal hsi_cod_empresa { get; set; }
        public decimal hsi_cod_empleado { get; set; }
        public decimal hsi_item { get; set; }
        public System.DateTime hsi_fecha_desde { get; set; }
        public decimal hsi_cod_situacion { get; set; }
    }
}
