//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_horas_extras
    {
        public decimal hor_cod_empresa { get; set; }
        public decimal hor_cod_empleado { get; set; }
        public System.DateTime hor_fecha { get; set; }
        public Nullable<decimal> hor_total { get; set; }
        public string hor_usuario { get; set; }
    }
}
