//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_feriados
    {
        public System.DateTime fer_fecha { get; set; }
        public string fer_motivo { get; set; }
        public decimal fer_nro_entrada { get; set; }
        public string fer_usuario { get; set; }
    }
}
