//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_solicitudes
    {
        public decimal sop_cod_empresa { get; set; }
        public decimal sop_nro_solicitud { get; set; }
        public System.DateTime sop_fecha { get; set; }
        public decimal sop_cod_empleado { get; set; }
        public decimal sop_tipo_solicitud { get; set; }
        public decimal sop_cant_horas { get; set; }
        public string sop_observacion { get; set; }
        public System.DateTime sop_fecha_carga { get; set; }
        public decimal sop_estado { get; set; }
        public decimal sop_nro_entrada { get; set; }
        public string sop_usuario { get; set; }
    
        public virtual rrhh_empleados rrhh_empleados { get; set; }
    }
}
