//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_descuentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rrhh_descuentos()
        {
            this.rrhh_descuentos_detalle = new HashSet<rrhh_descuentos_detalle>();
        }
    
        public decimal des_cod_empresa { get; set; }
        public decimal des_nro_descuento { get; set; }
        public System.DateTime des_fecha_carga { get; set; }
        public string des_login_carga { get; set; }
        public Nullable<System.DateTime> des_fecha_procesa { get; set; }
        public string des_login_procesa { get; set; }
        public decimal des_tipo_descuento { get; set; }
        public decimal des_cod_concepto { get; set; }
        public decimal des_importe { get; set; }
        public Nullable<decimal> des_nro_entrada_factura { get; set; }
        public Nullable<decimal> des_cod_cta_bancaria { get; set; }
        public string des_nro_cuenta_bancaria { get; set; }
        public decimal des_nro_entrada { get; set; }
        public string des_usuario { get; set; }
        public string des_observaciones { get; set; }
        public decimal des_cod_empleado { get; set; }
        public Nullable<decimal> des_tipo_pago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_descuentos_detalle> rrhh_descuentos_detalle { get; set; }
    }
}
