//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_referencias
    {
        public decimal ref_cod_empresa { get; set; }
        public decimal ref_cod_empleado { get; set; }
        public decimal ref_item { get; set; }
        public string ref_nombre { get; set; }
        public string ref_telefono { get; set; }
        public string ref_observaciones { get; set; }
        public decimal ref_nro_entrada { get; set; }
        public string ref_usuario { get; set; }
    
        public virtual rrhh_empleados rrhh_empleados { get; set; }
    }
}
