//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_turnos
    {
        public decimal tur_cod_empleado { get; set; }
        public System.DateTime tur_fecha { get; set; }
        public Nullable<System.TimeSpan> tur_hora_entrada1 { get; set; }
        public Nullable<System.TimeSpan> tur_hora_entrada2 { get; set; }
        public Nullable<System.TimeSpan> tur_hora_entrada3 { get; set; }
        public Nullable<System.TimeSpan> tur_hora_entrada4 { get; set; }
        public Nullable<System.TimeSpan> tur_hora_entrada5 { get; set; }
        public Nullable<System.TimeSpan> tur_hora_salida1 { get; set; }
        public Nullable<System.TimeSpan> tur_hora_salida2 { get; set; }
        public Nullable<System.TimeSpan> tur_hora_salida3 { get; set; }
        public Nullable<System.TimeSpan> tur_hora_salida4 { get; set; }
        public Nullable<System.TimeSpan> tur_hora_salida5 { get; set; }
        public string tur_usuario_genera { get; set; }
        public Nullable<System.DateTime> tur_fecha_genera { get; set; }
        public Nullable<System.TimeSpan> tur_hora_genera { get; set; }
    }
}
