//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_historico_salarios_minimo
    {
        public decimal hsa_cod_empresa { get; set; }
        public decimal hsa_item { get; set; }
        public System.DateTime hsa_fecha_desde { get; set; }
        public decimal hsa_importe { get; set; }
    }
}
