//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_conceptos_fijos
    {
        public decimal cfi_cod_empresa { get; set; }
        public decimal cfi_cod_empleado { get; set; }
        public decimal cfi_cod_concepto { get; set; }
        public decimal cfi_importe { get; set; }
        public decimal cfi_nro_entrada { get; set; }
        public string cfi_usuario { get; set; }
    
        public virtual rrhh_conceptos rrhh_conceptos { get; set; }
        public virtual rrhh_empleados rrhh_empleados { get; set; }
    }
}
