//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_liquidaciones_detalle
    {
        public decimal lid_cod_empresa { get; set; }
        public decimal lid_nro_liquidacion { get; set; }
        public decimal lid_item { get; set; }
        public decimal lid_cod_concepto { get; set; }
        public string lid_tipo { get; set; }
        public decimal lid_importe { get; set; }
        public string lid_ind_bloqueo { get; set; }
        public Nullable<decimal> lid_clave_poliza { get; set; }
        public Nullable<decimal> lid_cuota_poliza { get; set; }
        public Nullable<decimal> lid_clave_adelanto { get; set; }
        public Nullable<decimal> lid_cuota_adelanto { get; set; }
        public string lid_observacion { get; set; }
    
        public virtual rrhh_conceptos rrhh_conceptos { get; set; }
        public virtual rrhh_liquidaciones_cabeza rrhh_liquidaciones_cabeza { get; set; }
    }
}
