//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_descuentos_detalle
    {
        public decimal ded_cod_empresa { get; set; }
        public decimal ded_nro_descuento { get; set; }
        public decimal ded_nro_cuota { get; set; }
        public System.DateTime ded_vencimiento { get; set; }
        public decimal ded_importe { get; set; }
        public Nullable<decimal> ded_nro_liquidacion { get; set; }
        public decimal ded_nro_entrada { get; set; }
        public string ded_usuario { get; set; }
    
        public virtual rrhh_descuentos rrhh_descuentos { get; set; }
        public virtual rrhh_liquidaciones_cabeza rrhh_liquidaciones_cabeza { get; set; }
    }
}
