//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_vacaciones
    {
        public decimal vac_cod_empresa { get; set; }
        public decimal vac_cod_empleado { get; set; }
        public System.DateTime vac_fecha_desde { get; set; }
        public System.DateTime vac_fecha_hasta { get; set; }
        public decimal vac_dias_contabilizados { get; set; }
        public Nullable<decimal> vac_nro_solicitud { get; set; }
        public decimal vac_nro_entrada { get; set; }
        public string vac_usuario { get; set; }
    
        public virtual rrhh_empleados rrhh_empleados { get; set; }
        public virtual rrhh_solicitud_vacaciones rrhh_solicitud_vacaciones { get; set; }
    }
}
