//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_sucursales
    {
        public decimal suc_cod_empresa { get; set; }
        public decimal suc_codigo { get; set; }
        public string suc_descripcion { get; set; }
        public Nullable<decimal> suc_cod_encargado { get; set; }
        public decimal suc_cod_ciudad { get; set; }
        public string suc_direccion { get; set; }
        public string suc_telefono { get; set; }
        public string suc_fax { get; set; }
        public string suc_mail { get; set; }
        public decimal suc_emision { get; set; }
        public decimal suc_siniestros { get; set; }
        public decimal suc_cobranzas { get; set; }
        public decimal suc_nro_entrada { get; set; }
        public string suc_usuario { get; set; }
    
        public virtual rrhh_ciudades rrhh_ciudades { get; set; }
    }
}
