//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_departamentos_empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rrhh_departamentos_empresa()
        {
            this.rrhh_departamentos_empresa1 = new HashSet<rrhh_departamentos_empresa>();
            this.rrhh_empleados = new HashSet<rrhh_empleados>();
        }
    
        public decimal dep_cod_empresa { get; set; }
        public decimal dep_codigo { get; set; }
        public string dep_descripcion { get; set; }
        public Nullable<decimal> dep_cod_encargado { get; set; }
        public Nullable<decimal> dep_cod_dep_dependencia { get; set; }
        public decimal dep_nro_entrada { get; set; }
        public string dep_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_departamentos_empresa> rrhh_departamentos_empresa1 { get; set; }
        public virtual rrhh_departamentos_empresa rrhh_departamentos_empresa2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_empleados> rrhh_empleados { get; set; }
    }
}
