//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_liquidaciones_cabeza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rrhh_liquidaciones_cabeza()
        {
            this.rrhh_descuentos_detalle = new HashSet<rrhh_descuentos_detalle>();
            this.rrhh_liquidaciones_detalle = new HashSet<rrhh_liquidaciones_detalle>();
        }
    
        public decimal liq_cod_empresa { get; set; }
        public decimal liq_nro_liquidacion { get; set; }
        public System.DateTime liq_periodo_desde { get; set; }
        public System.DateTime liq_periodo_hasta { get; set; }
        public decimal liq_ind_aguinaldo { get; set; }
        public System.DateTime liq_fecha_genera { get; set; }
        public string liq_login_genera { get; set; }
        public Nullable<System.DateTime> liq_fecha_procesa { get; set; }
        public string liq_login_procesa { get; set; }
        public decimal liq_cod_empleado { get; set; }
        public decimal liq_salario_base { get; set; }
        public decimal liq_cant_hijos { get; set; }
        public decimal liq_bonificacion_familiar { get; set; }
        public decimal liq_vacaciones { get; set; }
        public decimal liq_otros_ingresos { get; set; }
        public decimal liq_pct_ips_empleado { get; set; }
        public decimal liq_ips_empleado { get; set; }
        public decimal liq_otros_egresos { get; set; }
        public decimal liq_total_debitos { get; set; }
        public decimal liq_total_creditos { get; set; }
        public decimal liq_salario_neto { get; set; }
        public decimal liq_pct_ips_patronal { get; set; }
        public decimal liq_ips_patronal { get; set; }
        public Nullable<decimal> liq_nro_entrada_factura { get; set; }
        public decimal liq_tipo_pago { get; set; }
        public string liq_cod_banco { get; set; }
        public string liq_nro_cuenta_bancaria { get; set; }
        public decimal liq_importe_a_acreditar { get; set; }
        public decimal liq_nro_entrada { get; set; }
        public string liq_usuario { get; set; }
        public decimal liq_dias_trabajados { get; set; }
        public decimal liq_sueldo_ips { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_descuentos_detalle> rrhh_descuentos_detalle { get; set; }
        public virtual rrhh_empleados rrhh_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_liquidaciones_detalle> rrhh_liquidaciones_detalle { get; set; }
        public virtual rrhh_tipos_pago rrhh_tipos_pago { get; set; }
    }
}
