//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_conceptos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rrhh_conceptos()
        {
            this.rrhh_conceptos_fijos = new HashSet<rrhh_conceptos_fijos>();
            this.rrhh_liquidaciones_detalle = new HashSet<rrhh_liquidaciones_detalle>();
        }
    
        public decimal con_cod_empresa { get; set; }
        public decimal con_codigo { get; set; }
        public string con_descripcion { get; set; }
        public decimal con_cod_grupo { get; set; }
        public string con_ind_fijo { get; set; }
        public string con_ind_aguinaldo { get; set; }
        public string con_ind_ips { get; set; }
        public string con_ind_mjt { get; set; }
        public string con_cta_contable { get; set; }
        public decimal con_nro_entrada { get; set; }
        public string con_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_conceptos_fijos> rrhh_conceptos_fijos { get; set; }
        public virtual rrhh_grupos_conceptos rrhh_grupos_conceptos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_liquidaciones_detalle> rrhh_liquidaciones_detalle { get; set; }
    }
}
