//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_grupos_conceptos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rrhh_grupos_conceptos()
        {
            this.rrhh_conceptos = new HashSet<rrhh_conceptos>();
        }
    
        public decimal gco_cod_empresa { get; set; }
        public decimal gco_codigo { get; set; }
        public string gco_descripcion { get; set; }
        public string gco_tipo { get; set; }
        public decimal gco_orden { get; set; }
        public decimal gco_nro_entrada { get; set; }
        public string gco_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_conceptos> rrhh_conceptos { get; set; }
    }
}
