//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_configuraciones
    {
        public decimal con_cod_empresa { get; set; }
        public decimal con_registro { get; set; }
        public System.TimeSpan con_hora_entrada { get; set; }
        public System.TimeSpan con_hora_salida_almuerzo { get; set; }
        public System.TimeSpan con_hora_entrada_almuerzo { get; set; }
        public System.TimeSpan con_hora_salida { get; set; }
        public System.TimeSpan con_hora_entrada_sabado { get; set; }
        public System.TimeSpan con_hora_salida_sabado { get; set; }
        public decimal con_salario_minimo_vigente { get; set; }
        public decimal con_nro_inscripcion_ips { get; set; }
        public decimal con_pct_ips_empleado { get; set; }
        public decimal con_pct_ips_patronal { get; set; }
        public decimal con_pct_bonificacion_familiar { get; set; }
        public decimal con_pct_salario_tope_bonif { get; set; }
        public decimal con_pct_hora_extra_normal { get; set; }
        public decimal con_pct_hora_extra_nocturno { get; set; }
        public decimal con_pct_hora_extra_feriado { get; set; }
        public decimal con_minutos_tolerancia_entrada { get; set; }
        public decimal con_minutos_tolerancia_alm { get; set; }
        public Nullable<decimal> con_concepto_salario { get; set; }
        public Nullable<decimal> con_concepto_ausencias { get; set; }
        public Nullable<decimal> con_concepto_llegadas_tardias { get; set; }
        public Nullable<decimal> con_concepto_horas_extras { get; set; }
        public Nullable<decimal> con_concepto_ips { get; set; }
        public Nullable<decimal> con_concepto_bonif_familiar { get; set; }
        public Nullable<decimal> con_concepto_adel_salario { get; set; }
        public Nullable<decimal> con_concepto_canc_adel_salario { get; set; }
        public Nullable<decimal> con_concepto_aguinaldo { get; set; }
        public Nullable<decimal> con_concepto_adel_aguinaldo { get; set; }
        public Nullable<decimal> con_concepto_canc_adel_agui { get; set; }
        public Nullable<decimal> con_concepto_vacaciones { get; set; }
        public Nullable<decimal> con_concepto_seguro { get; set; }
        public Nullable<decimal> con_concepto_telefono { get; set; }
        public Nullable<decimal> con_cobrador_rrhh { get; set; }
        public Nullable<decimal> con_cod_situacion_activo { get; set; }
        public Nullable<decimal> con_cod_hijo { get; set; }
        public Nullable<decimal> con_cod_conyuge { get; set; }
        public decimal con_nro_entrada { get; set; }
        public decimal con_concepto_redondeo_debito { get; set; }
        public decimal con_concepto_redondeo_credito { get; set; }
        public decimal con_redondeo { get; set; }
        public Nullable<decimal> con_cuenta_debito_empresa { get; set; }
        public Nullable<decimal> con_tipo_pago_acreditacion { get; set; }
    }
}
