//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_hist_departamentos_cargos
    {
        public decimal hdc_cod_empresa { get; set; }
        public decimal hdc_cod_empleado { get; set; }
        public decimal hdc_item { get; set; }
        public System.DateTime hdc_fecha { get; set; }
        public decimal hdc_cod_departamento { get; set; }
        public Nullable<decimal> hdc_cod_cargo { get; set; }
    }
}
