//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_relojes
    {
        public decimal rel_cod_empresa { get; set; }
        public decimal rel_cod_agcia { get; set; }
        public decimal rel_codigo { get; set; }
        public string rel_descripcion { get; set; }
        public Nullable<System.DateTime> rel_fecha_ultima_sincronizacion { get; set; }
        public string rel_hora_ult_sincro { get; set; }
        public string rel_usuario { get; set; }
        public string rel_ip { get; set; }
        public string rel_tipo_reloj { get; set; }
    }
}
