//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_justificativos
    {
        public decimal jus_cod_empresa { get; set; }
        public decimal jus_codigo { get; set; }
        public Nullable<decimal> jus_cod_empleado { get; set; }
        public Nullable<System.DateTime> jus_fecha { get; set; }
        public Nullable<decimal> jus_tipo_justificativo { get; set; }
        public string jus_comentario { get; set; }
        public Nullable<System.DateTime> jus_fecha_carga { get; set; }
        public Nullable<System.TimeSpan> jus_hora_carga { get; set; }
        public string jus_usuario_carga { get; set; }
        public Nullable<decimal> jus_estado_justificativo { get; set; }
        public string jus_comentario_estado { get; set; }
        public Nullable<decimal> jus_nro_entrada { get; set; }
    }
}
