//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhh_tipos_pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rrhh_tipos_pago()
        {
            this.rrhh_liquidaciones_cabeza = new HashSet<rrhh_liquidaciones_cabeza>();
        }
    
        public decimal tpa_cod_empresa { get; set; }
        public decimal tpa_codigo { get; set; }
        public string tpa_descripcion { get; set; }
        public decimal tpa_nro_entrada { get; set; }
        public string tpa_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rrhh_liquidaciones_cabeza> rrhh_liquidaciones_cabeza { get; set; }
    }
}
