//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class saldos_facturas
    {
        public decimal ano { get; set; }
        public decimal mes { get; set; }
        public decimal cod_empresa { get; set; }
        public decimal operacion { get; set; }
        public decimal nro_entrada { get; set; }
        public decimal abonado { get; set; }
        public decimal saldo { get; set; }
    }
}
