//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class security_objects
    {
        public string application { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string date { get; set; }
        public string pbl { get; set; }
        public string cmt { get; set; }
    }
}
