//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class series_documentos
    {
        public decimal cod_empresa { get; set; }
        public decimal tipo_documento { get; set; }
        public decimal item { get; set; }
        public decimal desde { get; set; }
        public decimal hasta { get; set; }
        public decimal ultimo_nro { get; set; }
        public decimal terminado { get; set; }
        public string usuario_carga { get; set; }
        public string usuario_termina { get; set; }
        public decimal nro_entrada { get; set; }
    
        public virtual tipos_documentos_series tipos_documentos_series { get; set; }
    }
}
