//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class sist_archivos
    {
        public decimal arc_origen { get; set; }
        public decimal arc_nro_entrada_registro { get; set; }
        public decimal arc_nro_item { get; set; }
        public string arc_nombre { get; set; }
        public string arc_direccion { get; set; }
        public string arc_fecha { get; set; }
        public string arc_formato { get; set; }
        public Nullable<decimal> arc_tamano { get; set; }
        public Nullable<System.DateTime> arc_fecha_carga { get; set; }
        public Nullable<System.TimeSpan> arc_hora_carga { get; set; }
        public string arc_login_carga { get; set; }
        public Nullable<decimal> arc_nro_entrada { get; set; }
        public Nullable<decimal> arc_cod_empresa { get; set; }
    }
}
