//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class sist_origen_archivos
    {
        public decimal ori_codigo { get; set; }
        public string ori_descripcion { get; set; }
        public string ori_nombre_carpeta { get; set; }
        public string ori_formato_archivo { get; set; }
        public Nullable<decimal> ori_nro_entrada { get; set; }
        public Nullable<decimal> ori_cod_empresa { get; set; }
    }
}
