//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class spatial_ref_sys
    {
        public int srid { get; set; }
        public string auth_name { get; set; }
        public Nullable<int> auth_srid { get; set; }
        public string srtext { get; set; }
        public string proj4text { get; set; }
    }
}
