//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class stk_remisiones_detalle
    {
        public decimal red_cod_empresa { get; set; }
        public decimal red_nro_remision { get; set; }
        public decimal red_item { get; set; }
        public Nullable<decimal> red_clave_venta { get; set; }
        public Nullable<decimal> red_cod_articulo { get; set; }
        public Nullable<decimal> red_cantidad { get; set; }
        public Nullable<decimal> red_tipo { get; set; }
        public Nullable<decimal> red_nro_mvto_caja { get; set; }
    
        public virtual stk_remisiones_cabeza stk_remisiones_cabeza { get; set; }
    }
}
