//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes_pinturas_detalle
    {
        public decimal opd_nro_orden { get; set; }
        public decimal opd_nro_item { get; set; }
        public decimal opd_cod_producto { get; set; }
        public decimal opd_cantidad { get; set; }
        public decimal opd_ajuste { get; set; }
        public decimal opd_total { get; set; }
        public decimal opd_porcentaje { get; set; }
        public decimal opd_nro_entrada { get; set; }
    
        public virtual tall_ordenes_pinturas_cab tall_ordenes_pinturas_cab { get; set; }
    }
}
