//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes_chaperia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tall_ordenes_chaperia()
        {
            this.tall_ordenes_tareas = new HashSet<tall_ordenes_tareas>();
        }
    
        public decimal och_nro_orden { get; set; }
        public decimal och_item { get; set; }
        public Nullable<decimal> och_clave_parte { get; set; }
        public decimal och_tipo_dano { get; set; }
        public string och_observaciones { get; set; }
        public decimal och_tipo_pago { get; set; }
        public decimal och_horas { get; set; }
        public decimal och_costo { get; set; }
        public decimal och_costo_loc { get; set; }
        public decimal och_costo_materiales { get; set; }
        public decimal och_costo_materiales_loc { get; set; }
        public Nullable<decimal> och_clave_presupuesto { get; set; }
        public decimal och_nro_entrada { get; set; }
        public Nullable<decimal> och_tipo_tarea { get; set; }
        public decimal och_pintar { get; set; }
    
        public virtual tall_ordenes tall_ordenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_ordenes_tareas> tall_ordenes_tareas { get; set; }
    }
}
