//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes_solicitudes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tall_ordenes_solicitudes()
        {
            this.tall_ordenes_solicitudes_detalle = new HashSet<tall_ordenes_solicitudes_detalle>();
        }
    
        public decimal sol_numero { get; set; }
        public decimal sol_clave_stock { get; set; }
        public decimal sol_cod_sucursal { get; set; }
        public System.DateTime sol_fecha { get; set; }
        public System.TimeSpan sol_hora { get; set; }
        public string sol_usuario { get; set; }
        public decimal sol_nro_orden { get; set; }
        public decimal sol_cod_deposito { get; set; }
        public decimal sol_cod_operacion { get; set; }
        public decimal sol_cod_tecnico { get; set; }
        public string sol_observaciones { get; set; }
        public decimal sol_nro_entrada { get; set; }
    
        public virtual tall_ordenes tall_ordenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_ordenes_solicitudes_detalle> tall_ordenes_solicitudes_detalle { get; set; }
    }
}
