//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_mantenimientos
    {
        public decimal tma_cod_mantenimiento { get; set; }
        public decimal tma_cod_marca { get; set; }
        public decimal tma_cod_modelo { get; set; }
        public decimal tma_cod_version { get; set; }
        public decimal tma_kilometraje { get; set; }
        public string tma_descripcion { get; set; }
        public decimal tma_nro_entrada { get; set; }
        public Nullable<decimal> tma_horas { get; set; }
    }
}
