//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes_notas
    {
        public decimal orn_nro_orden { get; set; }
        public decimal orn_nro_item { get; set; }
        public string orn_detalle_a_realizar { get; set; }
        public System.DateTime orn_fecha_carga { get; set; }
        public System.TimeSpan orn_hora_carga { get; set; }
        public string orn_usuario_carga { get; set; }
        public System.DateTime orn_fecha_a_realizar { get; set; }
        public System.TimeSpan orn_hora_a_realizar { get; set; }
        public string orn_usuario_a_realizar { get; set; }
        public string orn_detalle_realizado { get; set; }
        public Nullable<System.DateTime> orn_fecha_realizado { get; set; }
        public Nullable<System.TimeSpan> orn_hora_realizado { get; set; }
        public string orn_usuario_realizado { get; set; }
        public decimal orn_nro_entrada { get; set; }
    
        public virtual tall_ordenes tall_ordenes { get; set; }
    }
}
