//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_vehiculos
    {
        public decimal veh_codigo { get; set; }
        public decimal veh_cod_marca { get; set; }
        public decimal veh_cod_modelo { get; set; }
        public decimal veh_cod_version { get; set; }
        public string veh_marcmodever { get; set; }
        public decimal veh_ano { get; set; }
        public string veh_nro_chasis { get; set; }
        public string veh_nro_motor { get; set; }
        public string veh_nro_chapa { get; set; }
        public Nullable<decimal> veh_cod_color { get; set; }
        public decimal veh_imp_dir { get; set; }
        public decimal veh_ult_km { get; set; }
        public System.DateTime veh_fecha_ingreso { get; set; }
        public decimal veh_cod_cliente { get; set; }
        public decimal veh_estado { get; set; }
        public decimal veh_nro_entrada { get; set; }
        public Nullable<decimal> veh_liberar_kilometraje { get; set; }
        public string veh_habilitacion_municipio { get; set; }
        public Nullable<System.DateTime> veh_habilitacion_vto { get; set; }
        public string veh_poliza_aseguradora { get; set; }
        public Nullable<System.DateTime> veh_poliza_vto { get; set; }
        public Nullable<decimal> veh_poliza_nro { get; set; }
        public Nullable<System.DateTime> veh_dinatran_vto { get; set; }
        public Nullable<decimal> veh_dinatran_tara { get; set; }
        public Nullable<decimal> veh_limite_tara { get; set; }
        public string veh_codigo_rastreo { get; set; }
        public Nullable<decimal> veh_cod_chofer { get; set; }
        public Nullable<decimal> veh_clave_remision_actual { get; set; }
        public Nullable<decimal> veh_logistica { get; set; }
        public Nullable<decimal> veh_cod_empresa { get; set; }
        public string veh_observacion { get; set; }
        public Nullable<decimal> veh_agcia { get; set; }
    
        public virtual tall_colores_vehiculos tall_colores_vehiculos { get; set; }
        public virtual tall_versiones_vehiculos tall_versiones_vehiculos { get; set; }
    }
}
