//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes_repuestos
    {
        public decimal ore_nro_orden { get; set; }
        public decimal ore_item { get; set; }
        public Nullable<decimal> ore_cod_producto { get; set; }
        public decimal ore_cantidad { get; set; }
        public string ore_observaciones { get; set; }
        public decimal ore_tipo_pago { get; set; }
        public Nullable<decimal> ore_cod_proveedor { get; set; }
        public string ore_nro_presupuesto_proveedor { get; set; }
        public decimal ore_importe_proveedor { get; set; }
        public decimal ore_importe_proveedor_loc { get; set; }
        public decimal ore_importe_cliente { get; set; }
        public decimal ore_importe_cliente_loc { get; set; }
        public Nullable<System.DateTime> ore_fecha_recibe { get; set; }
        public Nullable<System.TimeSpan> ore_hora_recibe { get; set; }
        public string ore_usuario_recibe { get; set; }
        public Nullable<decimal> ore_clave_presupuesto { get; set; }
        public Nullable<decimal> ore_clave_factura_proveedor { get; set; }
        public decimal ore_nro_entrada { get; set; }
        public Nullable<decimal> ore_cod_empleado_solicita { get; set; }
        public Nullable<decimal> ore_cod_empleado_recibe { get; set; }
        public Nullable<decimal> ore_clave_prefactura { get; set; }
        public Nullable<decimal> ore_clave_factura { get; set; }
        public Nullable<decimal> ore_descuento { get; set; }
        public Nullable<decimal> ore_pct_descuento { get; set; }
        public string ore_usuario_modifica { get; set; }
        public Nullable<System.DateTime> ore_fecha_modifica { get; set; }
        public Nullable<System.TimeSpan> ore_hora_modifica { get; set; }
        public Nullable<decimal> ore_adicional { get; set; }
        public Nullable<decimal> ore_solicitado { get; set; }
        public Nullable<decimal> ore_reclamado { get; set; }
        public Nullable<decimal> ore_recibido { get; set; }
    
        public virtual tall_ordenes tall_ordenes { get; set; }
    }
}
