//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_recepcion
    {
        public decimal rec_clave_recepcion { get; set; }
        public decimal rec_cod_sucursal { get; set; }
        public string rec_motivo_entrada { get; set; }
        public decimal rec_nro_recepcion { get; set; }
        public Nullable<decimal> rec_tipo_servicio { get; set; }
        public System.DateTime rec_fecha_ingreso { get; set; }
        public System.TimeSpan rec_hora_ingreso { get; set; }
        public decimal rec_cod_cliente { get; set; }
        public Nullable<decimal> rec_cod_aseguradora { get; set; }
        public Nullable<decimal> rec_seccion { get; set; }
        public Nullable<decimal> rec_poliza { get; set; }
        public Nullable<decimal> rec_anexo { get; set; }
        public string rec_nro_stro { get; set; }
        public decimal rec_cod_vehiculo { get; set; }
        public decimal rec_cod_marca { get; set; }
        public decimal rec_cod_modelo { get; set; }
        public decimal rec_cod_version { get; set; }
        public string rec_marcmodever { get; set; }
        public decimal rec_ano { get; set; }
        public string rec_nro_chasis { get; set; }
        public string rec_nro_chapa { get; set; }
        public decimal rec_cod_color { get; set; }
        public decimal rec_kilometraje { get; set; }
        public string rec_objetos_personales { get; set; }
        public decimal rec_nivel_combustible_entrada { get; set; }
        public Nullable<decimal> rec_nivel_combustible_salida { get; set; }
        public string rec_observaciones { get; set; }
        public decimal rec_cod_cliente_facturar { get; set; }
        public string rec_nombre_facturar { get; set; }
        public string rec_ruc_facturar { get; set; }
        public decimal rec_cod_asesor { get; set; }
        public Nullable<decimal> rec_clave_ot { get; set; }
        public Nullable<decimal> rec_clave_ficha_presu { get; set; }
        public Nullable<System.DateTime> rec_fecha_salida { get; set; }
        public Nullable<System.TimeSpan> rec_hora_salida { get; set; }
        public System.DateTime rec_fecha_carga_ingreso { get; set; }
        public System.TimeSpan rec_hora_carga_ingreso { get; set; }
        public string rec_usuario_carga_ingreso { get; set; }
        public Nullable<System.DateTime> rec_fecha_impresion { get; set; }
        public Nullable<System.TimeSpan> rec_hora_impresion { get; set; }
        public string rec_login_impresion { get; set; }
        public Nullable<System.DateTime> rec_fecha_carga_salida { get; set; }
        public Nullable<System.TimeSpan> rec_hora_carga_salida { get; set; }
        public string rec_login__carga_salida { get; set; }
        public decimal rec_nro_entrada { get; set; }
        public decimal rec_kilometraje_mantenimiento { get; set; }
        public Nullable<decimal> rec_clave_salida { get; set; }
        public string rec_observacion_salida { get; set; }
        public Nullable<decimal> rec_x1 { get; set; }
        public Nullable<decimal> rec_y1 { get; set; }
        public string rec_indicador_tablero { get; set; }
        public Nullable<decimal> rec_cod_operador_seguro { get; set; }
    }
}
