//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_departamentos_cia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tall_departamentos_cia()
        {
            this.tall_tipos_tareas = new HashSet<tall_tipos_tareas>();
        }
    
        public decimal dep_codigo { get; set; }
        public string dep_descripcion { get; set; }
        public string dep_cuenta_contable { get; set; }
        public decimal dep_horas_dia { get; set; }
        public decimal dep_nro_entrada { get; set; }
        public decimal dep_costo_hora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_tipos_tareas> tall_tipos_tareas { get; set; }
    }
}
