//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes_controles
    {
        public decimal oco_nro_orden { get; set; }
        public decimal oco_nro_item { get; set; }
        public string oco_detalle { get; set; }
        public decimal oco_invalidante { get; set; }
        public decimal oco_corregido { get; set; }
        public Nullable<decimal> oco_tecnico { get; set; }
        public decimal oco_nro_entrada { get; set; }
        public string oco_comentario { get; set; }
        public Nullable<decimal> oco_pendiente { get; set; }
    
        public virtual tall_ordenes tall_ordenes { get; set; }
    }
}
