//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes_tareas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tall_ordenes_tareas()
        {
            this.tall_ordenes_tareas_detalle = new HashSet<tall_ordenes_tareas_detalle>();
        }
    
        public decimal oct_nro_orden { get; set; }
        public decimal oct_item { get; set; }
        public decimal oct_movimiento { get; set; }
        public Nullable<decimal> oct_cod_tarea_tiempo { get; set; }
        public string oct_descripcion_tarea { get; set; }
        public decimal oct_cod_departamento { get; set; }
        public decimal oct_tiempo { get; set; }
        public decimal oct_costo { get; set; }
        public decimal oct_costo_loc { get; set; }
        public decimal oct_costo_materiales { get; set; }
        public decimal oct_costo_materiales_loc { get; set; }
        public Nullable<decimal> oct_clave_presupuesto { get; set; }
        public decimal oct_nro_entrada { get; set; }
        public decimal oct_costo_hora { get; set; }
        public decimal oct_costo_hora_loc { get; set; }
        public Nullable<decimal> oct_clave_prefactura { get; set; }
        public Nullable<decimal> oct_clave_factura { get; set; }
        public Nullable<decimal> oct_marca_costo { get; set; }
        public string oct_usuario_modifica { get; set; }
        public Nullable<System.DateTime> oct_fecha_modifica { get; set; }
        public Nullable<System.TimeSpan> oct_hora_modifica { get; set; }
        public string oct_usuario_carga { get; set; }
        public Nullable<System.DateTime> oct_fecha_carga { get; set; }
        public Nullable<System.TimeSpan> oct_hora_carga { get; set; }
        public Nullable<decimal> oct_pct_descuento { get; set; }
        public Nullable<decimal> oct_descuento { get; set; }
        public Nullable<decimal> oct_costo_neto { get; set; }
    
        public virtual tall_ordenes_chaperia tall_ordenes_chaperia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_ordenes_tareas_detalle> tall_ordenes_tareas_detalle { get; set; }
    }
}
