//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes_pinturas_cab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tall_ordenes_pinturas_cab()
        {
            this.tall_ordenes_pinturas_detalle = new HashSet<tall_ordenes_pinturas_detalle>();
        }
    
        public decimal opi_nro_orden { get; set; }
        public decimal opi_nro_item { get; set; }
        public string opi_detalle { get; set; }
        public decimal opi_cantidad { get; set; }
        public decimal opi_nro_entrada { get; set; }
    
        public virtual tall_ordenes tall_ordenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_ordenes_pinturas_detalle> tall_ordenes_pinturas_detalle { get; set; }
    }
}
