//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes_materiales
    {
        public decimal ocm_nro_orden { get; set; }
        public decimal ocm_item { get; set; }
        public decimal ocm_movimiento { get; set; }
        public decimal ocm_cod_producto { get; set; }
        public decimal ocm_cantidad { get; set; }
        public decimal ocm_costo_unitario { get; set; }
        public decimal ocm_costo_unitario_loc { get; set; }
        public decimal ocm_costo { get; set; }
        public decimal ocm_costo_loc { get; set; }
        public decimal ocm_precio_cliente { get; set; }
        public decimal ocm_precio_cliente_loc { get; set; }
        public Nullable<decimal> ocm_clave_presupuesto { get; set; }
        public decimal ocm_nro_entrada { get; set; }
        public Nullable<decimal> ocm_clave_prefactura { get; set; }
        public Nullable<decimal> ocm_clave_factura { get; set; }
        public decimal ocm_nro_mvto { get; set; }
        public string ocm_usuario_modifica { get; set; }
        public Nullable<System.DateTime> ocm_fecha_modifica { get; set; }
        public Nullable<System.TimeSpan> ocm_hora_modifica { get; set; }
    }
}
