//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes_fotos
    {
        public decimal ofo_nro_orden { get; set; }
        public decimal ofo_nro_item { get; set; }
        public string ofo_archivo { get; set; }
        public decimal ofo_nro_entrada { get; set; }
    
        public virtual tall_ordenes tall_ordenes { get; set; }
    }
}
