//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes_solicitudes_detalle
    {
        public decimal sod_nro_movimiento { get; set; }
        public decimal sod_nro_item { get; set; }
        public decimal sod_cod_producto { get; set; }
        public string sod_detalle { get; set; }
        public decimal sod_cantidad { get; set; }
        public decimal sod_costo_unitario { get; set; }
        public decimal sod_costo_total { get; set; }
        public decimal sod_precio_unitario { get; set; }
        public decimal sod_precio_total { get; set; }
        public decimal sod_nro_entrada { get; set; }
        public Nullable<decimal> cod_articulo { get; set; }
    
        public virtual tall_ordenes_solicitudes tall_ordenes_solicitudes { get; set; }
    }
}
