//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tall_ordenes()
        {
            this.tall_ordenes_chaperia = new HashSet<tall_ordenes_chaperia>();
            this.tall_ordenes_controles = new HashSet<tall_ordenes_controles>();
            this.tall_ordenes_notas = new HashSet<tall_ordenes_notas>();
            this.tall_ordenes_repuestos = new HashSet<tall_ordenes_repuestos>();
            this.tall_ordenes_solicitudes = new HashSet<tall_ordenes_solicitudes>();
            this.tall_ordenes_terceros = new HashSet<tall_ordenes_terceros>();
            this.tall_ordenes_pinturas_cab = new HashSet<tall_ordenes_pinturas_cab>();
            this.tall_prefactura = new HashSet<tall_prefactura>();
            this.tall_ordenes_fotos = new HashSet<tall_ordenes_fotos>();
        }
    
        public decimal ord_nro_orden { get; set; }
        public decimal ord_cod_sucursal { get; set; }
        public decimal ord_cod_asesor { get; set; }
        public Nullable<decimal> ord_cod_moneda { get; set; }
        public Nullable<decimal> ord_tasa_cambio { get; set; }
        public Nullable<decimal> ord_costo_hora { get; set; }
        public Nullable<decimal> ord_costo_hora_loc { get; set; }
        public decimal ord_cod_cliente { get; set; }
        public Nullable<decimal> ord_cod_aseguradora { get; set; }
        public decimal ord_cod_vehiculo { get; set; }
        public decimal ord_cod_marca { get; set; }
        public decimal ord_cod_modelo { get; set; }
        public decimal ord_cod_version { get; set; }
        public string ord_marcmodever { get; set; }
        public decimal ord_ano { get; set; }
        public string ord_nro_chasis { get; set; }
        public string ord_nro_chapa { get; set; }
        public decimal ord_cod_color { get; set; }
        public Nullable<decimal> ord_seccion { get; set; }
        public Nullable<decimal> ord_poliza { get; set; }
        public Nullable<decimal> ord_anexo { get; set; }
        public string ord_nro_stro { get; set; }
        public string ord_encargado_seguro { get; set; }
        public string ord_telefono_encargado { get; set; }
        public string ord_email_encargado { get; set; }
        public decimal ord_estado { get; set; }
        public Nullable<System.DateTime> ord_fecha_a_entregar { get; set; }
        public Nullable<System.DateTime> ord_fecha_salida { get; set; }
        public Nullable<System.TimeSpan> ord_hora_salida { get; set; }
        public string ord_usuario_salida { get; set; }
        public string ord_observacion_salida { get; set; }
        public Nullable<System.DateTime> ord_fecha_carta { get; set; }
        public Nullable<System.TimeSpan> ord_hora_carta { get; set; }
        public string ord_usuario_carta { get; set; }
        public string ord_observacion_carta { get; set; }
        public System.DateTime ord_fecha_modificacion { get; set; }
        public System.TimeSpan ord_hora_modificacion { get; set; }
        public string ord_usuario_modificacion { get; set; }
        public decimal ord_nro_entrada { get; set; }
        public Nullable<System.TimeSpan> ord_hora_a_entregar { get; set; }
        public System.DateTime ord_fecha_apertura { get; set; }
        public System.TimeSpan ord_hora_apertura { get; set; }
        public Nullable<decimal> ord_control_calidad { get; set; }
        public string ord_usuario_control { get; set; }
        public Nullable<System.DateTime> ord_fecha_control { get; set; }
        public Nullable<System.TimeSpan> ord_hora_control { get; set; }
        public Nullable<decimal> ord_nro_lavadero { get; set; }
        public Nullable<decimal> ord_cod_tecnico_lavadero { get; set; }
        public Nullable<System.TimeSpan> ord_hora_inicio_lavado { get; set; }
        public Nullable<System.TimeSpan> ord_fecha_fin_lavado { get; set; }
        public Nullable<System.DateTime> ord_fecha_autorizacion_credito { get; set; }
        public Nullable<System.TimeSpan> ord_hora_autorizacion_credito { get; set; }
        public string ord_usuario_autorizacion_credit { get; set; }
        public Nullable<decimal> ord_kilometraje { get; set; }
        public Nullable<decimal> ord_clave_salida { get; set; }
        public Nullable<decimal> ord_servicio_prueba { get; set; }
        public string ord_usuario_serv_prueba { get; set; }
        public Nullable<System.DateTime> ord_fecha_serv_prueba { get; set; }
        public Nullable<System.TimeSpan> ord_hora_inicio_serv_prueba { get; set; }
        public Nullable<System.TimeSpan> ord_hora_fin_serv_prueba { get; set; }
        public Nullable<decimal> ord_control_llamada { get; set; }
        public string ord_llamada_observarcion { get; set; }
        public Nullable<System.DateTime> ord_fecha_llamada { get; set; }
        public Nullable<System.TimeSpan> ord_hora_inicion_llamada { get; set; }
        public Nullable<System.TimeSpan> ord_hora_fin_llamada { get; set; }
        public Nullable<decimal> ord_estado_trabajos { get; set; }
        public Nullable<decimal> ord_pintado { get; set; }
        public Nullable<System.DateTime> ord_fecha_pintura { get; set; }
        public Nullable<System.DateTime> ord_fecha_proceso_final { get; set; }
        public string ord_observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_ordenes_chaperia> tall_ordenes_chaperia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_ordenes_controles> tall_ordenes_controles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_ordenes_notas> tall_ordenes_notas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_ordenes_repuestos> tall_ordenes_repuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_ordenes_solicitudes> tall_ordenes_solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_ordenes_terceros> tall_ordenes_terceros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_ordenes_pinturas_cab> tall_ordenes_pinturas_cab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_prefactura> tall_prefactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_ordenes_fotos> tall_ordenes_fotos { get; set; }
    }
}
