//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_fichas_presupuestos
    {
        public decimal pre_nro_ficha { get; set; }
        public decimal pre_cod_sucursal { get; set; }
        public decimal pre_tipo_presupuesto { get; set; }
        public decimal pre_cod_asesor { get; set; }
        public decimal pre_cod_tecnico { get; set; }
        public Nullable<decimal> pre_cod_moneda { get; set; }
        public Nullable<decimal> pre_tasa_cambio { get; set; }
        public Nullable<decimal> pre_costo_hora { get; set; }
        public Nullable<decimal> pre_costo_hora_loc { get; set; }
        public decimal pre_cod_cliente { get; set; }
        public Nullable<decimal> pre_cod_aseguradora { get; set; }
        public decimal pre_cod_vehiculo { get; set; }
        public decimal pre_cod_marca { get; set; }
        public decimal pre_cod_modelo { get; set; }
        public decimal pre_cod_version { get; set; }
        public string pre_marcmodever { get; set; }
        public decimal pre_ano { get; set; }
        public string pre_nro_chasis { get; set; }
        public string pre_nro_chapa { get; set; }
        public decimal pre_cod_color { get; set; }
        public Nullable<decimal> pre_seccion { get; set; }
        public Nullable<decimal> pre_poliza { get; set; }
        public Nullable<decimal> pre_anexo { get; set; }
        public string pre_nro_stro { get; set; }
        public string pre_encargado_seguro { get; set; }
        public string pre_telefono_encargado { get; set; }
        public string pre_email_encargado { get; set; }
        public Nullable<decimal> pre_clave_recepcion { get; set; }
        public Nullable<decimal> pre_clave_ot { get; set; }
        public decimal pre_nro_presupuesto_cliente { get; set; }
        public decimal pre_estado_cliente { get; set; }
        public Nullable<System.DateTime> pre_fecha_autoriza_cliente { get; set; }
        public Nullable<System.TimeSpan> pre_hora_autoriza_cliente { get; set; }
        public string pre_usuario_autoriza_cliente { get; set; }
        public string pre_observacion_autoriza_cliente { get; set; }
        public Nullable<System.DateTime> pre_fecha_aprobacion_cliente { get; set; }
        public Nullable<System.TimeSpan> pre_hora_aprobacion_cliente { get; set; }
        public string pre_usuario_aprobacion_cliente { get; set; }
        public Nullable<decimal> pre_cod_motivo_rechazo_cliente { get; set; }
        public string pre_observacion_aprobacion_cliente { get; set; }
        public string pre_confirmado_con_cliente { get; set; }
        public decimal pre_nro_presupuesto_seguro { get; set; }
        public decimal pre_estado_seguro { get; set; }
        public Nullable<System.DateTime> pre_fecha_autoriza_seguro { get; set; }
        public Nullable<System.TimeSpan> pre_hora_autoriza_seguro { get; set; }
        public string pre_usuario_autoriza_seguro { get; set; }
        public string pre_observacion_autoriza_seguro { get; set; }
        public Nullable<System.DateTime> pre_fecha_aprobacion_seguro { get; set; }
        public Nullable<System.TimeSpan> pre_hora_aprobacion_seguro { get; set; }
        public string pre_usuario_aprobacion_seguro { get; set; }
        public Nullable<decimal> pre_cod_motivo_rechazo_seguro { get; set; }
        public string pre_observacion_aprobacion_seguro { get; set; }
        public string pre_confirmado_con_seguro { get; set; }
        public Nullable<System.DateTime> pre_fecha_entrada_taller { get; set; }
        public Nullable<System.DateTime> pre_fecha_entrega_estimada { get; set; }
        public string pre_observaciones { get; set; }
        public Nullable<decimal> pre_clave_factura_cliente { get; set; }
        public Nullable<decimal> pre_clave_factura_seguro { get; set; }
        public System.DateTime pre_fecha_carga { get; set; }
        public System.TimeSpan pre_hora_carga { get; set; }
        public string pre_usuario_carga { get; set; }
        public Nullable<System.DateTime> pre_fecha_impresion { get; set; }
        public Nullable<System.TimeSpan> pre_hora_impresion { get; set; }
        public string pre_usuario_impresion { get; set; }
        public System.DateTime pre_fecha_modificacion { get; set; }
        public System.TimeSpan pre_hora_modificacion { get; set; }
        public string pre_usuario_modificacion { get; set; }
        public decimal pre_nro_entrada { get; set; }
        public Nullable<decimal> pre_kilometraje { get; set; }
        public decimal pre_nro_aprobacion { get; set; }
        public Nullable<System.DateTime> pre_fecha_turno { get; set; }
        public string pre_usuario_turno { get; set; }
        public string pre_usuario_envia_correo { get; set; }
        public Nullable<System.DateTime> pre_fecha_envia_correo { get; set; }
        public Nullable<System.TimeSpan> pre_hora_envia_correo { get; set; }
    
        public virtual tall_motivos_rechazo tall_motivos_rechazo { get; set; }
        public virtual tall_motivos_rechazo tall_motivos_rechazo1 { get; set; }
    }
}
