//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes_tareas_detalle
    {
        public decimal otd_nro_orden { get; set; }
        public decimal otd_item { get; set; }
        public decimal otd_movimiento { get; set; }
        public decimal otd_nro_mvto { get; set; }
        public decimal otd_retrabajo { get; set; }
        public decimal otd_cod_tecnico { get; set; }
        public Nullable<decimal> otd_cod_tecnico_retrabajo { get; set; }
        public Nullable<System.DateTime> otd_fecha_inicio { get; set; }
        public Nullable<System.TimeSpan> otd_hora_inicio { get; set; }
        public Nullable<System.DateTime> otd_fecha_fin { get; set; }
        public Nullable<System.TimeSpan> otd_hora_fin { get; set; }
        public decimal otd_estado { get; set; }
        public string otd_comentario { get; set; }
        public System.DateTime otd_fecha_carga { get; set; }
        public System.TimeSpan otd_hora_carga { get; set; }
        public string otd_usuario_carga { get; set; }
    
        public virtual tall_ordenes_tareas tall_ordenes_tareas { get; set; }
    }
}
