//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_tipos_trabajos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tall_tipos_trabajos()
        {
            this.tall_tipos_tareas = new HashSet<tall_tipos_tareas>();
        }
    
        public decimal tta_codigo { get; set; }
        public string tta_descripcion { get; set; }
        public decimal tta_nro_entrada { get; set; }
        public string tta_nombre_corto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_tipos_tareas> tall_tipos_tareas { get; set; }
    }
}
