//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_tareas_tiempos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tall_tareas_tiempos()
        {
            this.tall_tareas_materiales = new HashSet<tall_tareas_materiales>();
        }
    
        public decimal tti_codigo { get; set; }
        public decimal tti_cod_tarea { get; set; }
        public decimal tti_tipo_pieza { get; set; }
        public decimal tti_tipo_dano { get; set; }
        public decimal tti_tiempo { get; set; }
        public Nullable<decimal> tti_nro_entrada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_tareas_materiales> tall_tareas_materiales { get; set; }
        public virtual tall_tipos_tareas tall_tipos_tareas { get; set; }
        public virtual tall_tipos_piezas tall_tipos_piezas { get; set; }
        public virtual tall_tipos_danos tall_tipos_danos { get; set; }
    }
}
