//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_tipos_pagos
    {
        public decimal tpa_codigo { get; set; }
        public string tpa_descripcion { get; set; }
        public Nullable<decimal> tpa_cod_cliente { get; set; }
        public decimal tpa_nro_entrada { get; set; }
        public decimal tpa_facturar { get; set; }
    }
}
