//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_modelos_vehiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tall_modelos_vehiculos()
        {
            this.tall_partes_vehiculos = new HashSet<tall_partes_vehiculos>();
            this.tall_versiones_vehiculos = new HashSet<tall_versiones_vehiculos>();
        }
    
        public decimal mod_cod_marca { get; set; }
        public decimal mod_cod_modelo { get; set; }
        public decimal mod_cod_tipo { get; set; }
        public string mod_descripcion { get; set; }
        public decimal mod_estado { get; set; }
        public decimal mod_nro_entrada { get; set; }
    
        public virtual tall_marcas_vehiculos tall_marcas_vehiculos { get; set; }
        public virtual tall_tipos_vehiculos tall_tipos_vehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_partes_vehiculos> tall_partes_vehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tall_versiones_vehiculos> tall_versiones_vehiculos { get; set; }
    }
}
