//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_partes_vehiculos
    {
        public decimal pve_clave_parte { get; set; }
        public decimal pve_cod_marca { get; set; }
        public decimal pve_cod_modelo { get; set; }
        public decimal pve_cod_parte { get; set; }
        public Nullable<decimal> pve_tipo_pieza { get; set; }
        public decimal pve_medida { get; set; }
        public decimal pve_maximo_pintura { get; set; }
        public decimal pve_nro_entrada { get; set; }
    
        public virtual tall_modelos_vehiculos tall_modelos_vehiculos { get; set; }
        public virtual tall_partes tall_partes { get; set; }
        public virtual tall_tipos_piezas tall_tipos_piezas { get; set; }
    }
}
