//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tall_ordenes_anotaciones
    {
        public decimal not_nro_orden { get; set; }
        public decimal not_nro_item { get; set; }
        public string not_detalle { get; set; }
        public System.DateTime not_fecha_carga { get; set; }
        public System.TimeSpan not_hora_carga { get; set; }
        public string not_usuario_carga { get; set; }
        public decimal not_nro_entrada { get; set; }
    }
}
