//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_operaciones_bancos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipos_operaciones_bancos()
        {
            this.operaciones_bancarias_cab = new HashSet<operaciones_bancarias_cab>();
        }
    
        public decimal tipo_operacion { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> operacion_borrador { get; set; }
        public string concepto { get; set; }
        public Nullable<decimal> operacion_borrador_elimina { get; set; }
        public Nullable<decimal> tipo_comprobante { get; set; }
        public string concepto_conciliacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operaciones_bancarias_cab> operaciones_bancarias_cab { get; set; }
        public virtual operaciones_borrador operaciones_borrador { get; set; }
    }
}
