//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipos_articulos()
        {
            this.articulos = new HashSet<articulos>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal tipo_articulo { get; set; }
        public string descripcion { get; set; }
        public string usuario { get; set; }
        public decimal nro_entrada { get; set; }
        public decimal pct_uno { get; set; }
        public decimal cantidad_uno { get; set; }
        public decimal pct_dos { get; set; }
        public decimal cantidad_dos { get; set; }
        public decimal pct_tres { get; set; }
        public decimal cantidad_tres { get; set; }
        public decimal pct_lista { get; set; }
        public Nullable<decimal> familia_articulo { get; set; }
        public decimal cantidad_cuatro { get; set; }
        public decimal pct_cuatro { get; set; }
        public decimal cantidad_cinco { get; set; }
        public decimal pct_cinco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulos> articulos { get; set; }
        public virtual empresas empresas { get; set; }
    }
}
