//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipos_facturas()
        {
            this.facturas_cab = new HashSet<facturas_cab>();
        }
    
        public decimal cod_empresa { get; set; }
        public decimal operacion { get; set; }
        public decimal tipo_factura { get; set; }
        public string descripcion { get; set; }
        public string cta_contable { get; set; }
        public Nullable<decimal> tipo_documento { get; set; }
        public string usuario { get; set; }
        public decimal nro_entrada { get; set; }
        public string dw_impresion { get; set; }
        public Nullable<decimal> utiliza_serie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturas_cab> facturas_cab { get; set; }
        public virtual operaciones_facturas operaciones_facturas { get; set; }
        public virtual tipos_documentos_series tipos_documentos_series { get; set; }
        public virtual tipos_documentos_series tipos_documentos_series1 { get; set; }
    }
}
