//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios_empresas()
        {
            this.cajas_habilitaciones = new HashSet<cajas_habilitaciones>();
        }
    
        public decimal cod_empresa { get; set; }
        public string userid { get; set; }
        public string usuario { get; set; }
        public decimal nro_entrada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas_habilitaciones> cajas_habilitaciones { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
