//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.auditoria = new HashSet<auditoria>();
            this.borrador = new HashSet<borrador>();
            this.borrador1 = new HashSet<borrador>();
            this.cotizaciones = new HashSet<cotizaciones>();
            this.empresas = new HashSet<empresas>();
            this.periodos_fiscales = new HashSet<periodos_fiscales>();
            this.permisos = new HashSet<permisos>();
            this.plan_cuentas = new HashSet<plan_cuentas>();
            this.usuarios_modulos = new HashSet<usuarios_modulos>();
            this.usuarios_empresas = new HashSet<usuarios_empresas>();
            this.usuarios_modulos1 = new HashSet<usuarios_modulos>();
        }
    
        public string userid { get; set; }
        public string nombre { get; set; }
        public string contrasena { get; set; }
        public decimal tipo_usuario { get; set; }
        public decimal cod_modulo { get; set; }
        public decimal estado { get; set; }
        public string usuario { get; set; }
        public decimal nro_entrada { get; set; }
        public decimal cod_usuario { get; set; }
        public string email { get; set; }
        public Nullable<decimal> nro_cedula { get; set; }
        public Nullable<decimal> cod_agcia { get; set; }
        public string huella_01 { get; set; }
        public string huella_02 { get; set; }
        public string huella_03 { get; set; }
        public Nullable<decimal> cod_persona { get; set; }
        public string estado_web { get; set; }
        public string contra_web { get; set; }
        public Nullable<decimal> limite_autoriza_gs { get; set; }
        public Nullable<decimal> limite_autoriza_me { get; set; }
        public string codigo_autorizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auditoria> auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrador> borrador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrador> borrador1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizaciones> cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empresas> empresas { get; set; }
        public virtual modulos_sistema modulos_sistema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<periodos_fiscales> periodos_fiscales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<permisos> permisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plan_cuentas> plan_cuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios_modulos> usuarios_modulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios_empresas> usuarios_empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios_modulos> usuarios_modulos1 { get; set; }
    }
}
