//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas_online
    {
        public decimal cod_empresa { get; set; }
        public decimal nro_caja { get; set; }
        public decimal item { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> total { get; set; }
        public string origen { get; set; }
        public string nombre_articulo { get; set; }
        public Nullable<decimal> cantidad { get; set; }
    }
}
